import {TreeNode} from "primereact/treenode";
import {databases} from "./appwrite";
import {ID, Query} from "appwrite";
import {FinancialLineDTO} from "./types/financial/line/dto/FinancialLineDTO";
import {Financial} from "./types/financial/Financial";
import {FinancialLineType} from "./types/financial/line/FinancialLineType";

export const BeyannameCodes: {
    [key: string]: any
} = {
    "I.": {name: "DÖNEN VARLIKLAR", accountCode: "1"},
    "I.A.": {name: "HAZIR DEĞERLER", accountCode: "10"},
    "I.A.1.": {name: "KASA", accountCode: "100"},
    "I.A.2.": {name: "ALINAN ÇEKLER", accountCode: "101"},
    "I.A.3.": {name: "BANKALAR", accountCode: "102"},
    "I.A.4.": {name: "VERİLEN ÇEKLER VE ÖDEME EMİRLERİ (-)", accountCode: "103"},
    "I.A.5.": {name: "DİĞER HAZIR DEĞERLER", accountCode: "108"},
    "I.B.": {name: "MENKUL KIYMETLER", accountCode: "11"},
    "I.B.1.": {name: "HİSSE SENETLERİ", accountCode: "110"},
    "I.B.2.": {name: "ÖZEL KESİM TAHVİL, SENET VE BONOLARI", accountCode: "111"},
    "I.B.3.": {name: "KAMU KESİMİ TAHVİL, SENET VE BONOLARI", accountCode: "112"},
    "I.B.4.": {name: "DİĞER MENKUL KIYMETLER", accountCode: "118"},
    "I.B.10.": {name: "MENKUL KIYMETLER DEĞER DÜŞÜKLÜĞÜ KARŞILIĞI (-)", accountCode: "119"},
    "I.C.": {name: "TİCARİ ALACAKLAR", accountCode: "12"},
    "I.C.1.": {name: "ALICILAR", accountCode: "120"},
    "I.C.2.": {name: "ALACAK SENETLERİ", accountCode: "121"},
    "I.C.3.": {name: "ALACAK SENETLERİ REESKONTU (-)", accountCode: "122"},
    "I.C.4.": {name: "KAZANILMAMIŞ FİNANSAL KİRALAMA FAİZ GELİRLERİ (-)", accountCode: "124"},
    "I.C.5.": {name: "VERİLEN DEPOZİTO VE TEMİNATLAR", accountCode: "126"},
    "I.C.6.": {name: "DİĞER TİCARİ ALACAKLAR SENET VE BONOLARI", accountCode: "127"},
    "I.C.7.": {name: "ŞÜPHELİ TİCARİ ALACAKLAR", accountCode: "128"},
    "I.C.8.": {name: "ŞÜPHELİ TİCARİ ALACAKLAR KARŞILIĞI (-)", accountCode: "129"},
    "I.D.": {name: "DİĞER ALACAKLAR", accountCode: "13"},
    "I.D.1.": {name: "ORTAKLARDAN ALACAKLAR", accountCode: "131"},
    "I.D.2.": {name: "İŞTİRAKLERDEN ALACAKLAR", accountCode: "132"},
    "I.D.3.": {name: "BAĞLI ORTAKLIKLARDAN ALACAKLAR", accountCode: "133"},
    "I.D.5.": {name: "PERSONELDEN ALACAKLAR", accountCode: "135"},
    "I.D.6.": {name: "DİĞER ÇEŞİTLİ ALACAKLAR", accountCode: "136"},
    "I.D.7.": {name: "DİĞER ALACAK SENETLERİ REESKONTU (-)", accountCode: "137"},
    "I.D.8.": {name: "ŞÜPHELİ DİĞER ALACAKLAR", accountCode: "138"},
    "I.D.9.": {name: "ŞÜPHELİ DİĞER ALACAKLAR KARŞILIĞI (-)", accountCode: "139"},
    "I.E.": {name: "STOKLAR", accountCode: "15"},
    "I.E.1.": {name: "İLK MADDE VE MALZEME", accountCode: "150"},
    "I.E.2.": {name: "YARI MAMULLER - ÜRETİM", accountCode: "151"},
    "I.E.3.": {name: "MAMÜLLER", accountCode: "152"},
    "I.E.4.": {name: "TİCARİ MALLAR", accountCode: "153"},
    "I.E.5.": {name: "DİĞER STOKLAR", accountCode: "157"},
    "I.E.6.": {name: "STOK DEĞER DÜŞÜKLÜĞÜ KARŞILIĞI (-)", accountCode: "158"},
    "I.E.7.": {name: "VERİLEN SİPARİŞ AVANSLARI", accountCode: "159"},
    "I.G.": {name: "GELECEK AYLARA AİT GİDERLER VE GELİR TAHAKKUKLARI", accountCode: "18"},
    "I.G.1.": {name: "GELECEK AYLARA AİT GİDERLER", accountCode: "180"},
    "I.G.2.": {name: "GELİR TAHAKKUKLARI", accountCode: "181"},
    "I.H.": {name: "DİĞER DÖNEN VARLIKLAR", accountCode: "19"},
    "I.H.1.": {name: "İNDİRİLECEK KATMA DEĞER VERGİSİ", accountCode: "191"},
    "I.H.2.": {name: "DİĞER KATMA DEĞER VERGİSİ", accountCode: "192"},
    "I.H.3.": {name: "PEŞİN ÖDENEN VERGİLER VE FONLAR", accountCode: "193"},
    "I.H.4.": {name: "PERSONEL AVANSLARI", accountCode: "196"},
    "I.H.5.": {name: "SAYIM VE TESELLÜM NOKSANLARI", accountCode: "197"},
    "I.H.6.": {name: "DİĞER ÇEŞİTLİ DÖNEN VARLIKLAR", accountCode: "198"},
    "I.H.7.": {name: "DİĞER DÖNEN VARLIKLAR KARŞILIĞI (-)", accountCode: "199"},
    "II.": {name: "DURAN VARLIKLAR", accountCode: "2"},
    "II.A.": {name: "TİCARİ ALACAKLAR", accountCode: "22"},
    "II.A.1.": {name: "ALICILAR", accountCode: "220"},
    "II.A.2.": {name: "ALACAK SENETLERİ", accountCode: "221"},
    "II.A.3.": {name: "ALACAK SENETLERİ REESKONTU (-)", accountCode: "222"},
    "II.A.4.": {name: "VERİLEN DEPOZİTO VE TEMİNATLAR", accountCode: "226"},
    "II.A.5.": {name: "ŞÜPHELİ ALACAKLAR KARŞILIĞI (-)", accountCode: "229"},
    "II.B.": {name: "DİĞER ALACAKLAR", accountCode: "23"},
    "II.B.1.": {name: "ORTAKLARDAN ALACAKLAR", accountCode: "230"},
    "II.B.2.": {name: "İŞTİRAKLERDEN ALACAKLAR", accountCode: "231"},
    "II.B.3.": {name: "BAĞLI ORTAKLIKLARDAN ALACAKLAR", accountCode: "232"},
    "II.B.4.": {name: "PERSONELDEN ALACAKLAR", accountCode: "235"},
    "II.B.5.": {name: "DİĞER ÇEŞİTLİ ALACAKLAR", accountCode: "236"},
    "II.B.6.": {name: "DİĞER ALACAK SENETLERİ REESKONTU (-)", accountCode: "237"},
    "II.B.7.": {name: "ŞÜPHELİ DİĞER ALACAKLAR KARŞILIĞI (-)", accountCode: "239"},
    "II.C.": {name: "MALİ DURAN VARLIKLAR", accountCode: "24"},
    "II.C.1.": {name: "BAĞLI MENKUL KIYMETLER", accountCode: "240"},
    "II.C.2.": {name: "BAĞLI MENKUL KIYMETLER DEĞER DÜŞÜKLÜĞÜ KARŞILIĞI (-)", accountCode: "241"},
    "II.C.3.": {name: "İŞTİRAKLER", accountCode: "242"},
    "II.C.4.": {name: "İŞTİRAKLERE SERMAYE TAAHHÜTLERİ (-)", accountCode: "243"},
    "II.C.5.": {name: "İŞTİRAKLER SERMAYE PAYLARI DEĞER DÜŞÜKLÜĞÜ KARŞILIĞI (-)", accountCode: "244"},
    "II.C.6.": {name: "BAĞLI ORTAKLIKLAR", accountCode: "245"},
    "II.C.7.": {name: "BAĞLI ORTAKLIKLARA SERMAYE TAAHHÜTLERİ (-)", accountCode: "246"},
    "II.C.8.": {name: "BAĞLI ORTAKLIKLAR SERMAYE PAYLARI DEĞER DÜŞÜKLÜGÜ KARŞILIĞI (-)", accountCode: "247"},
    "II.C.9.": {name: "DİĞER MALİ DURAN VARLIKLAR", accountCode: "248"},
    "II.C.10.": {name: "DİĞER MALİ DURAN VARLIKLAR KARŞILIĞI (-)", accountCode: "249"},
    "II.D.": {name: "MADDİ DURAN VARLIKLAR", accountCode: "25"},
    "II.D.1.": {name: "ARAZİ VE ARSALAR", accountCode: "250"},
    "II.D.2.": {name: "YER ALTI VE YER ÜSTÜ DÜZENLERİ", accountCode: "251"},
    "II.D.3.": {name: "BİNALAR", accountCode: "252"},
    "II.D.4.": {name: "TESİS, MAKİNE VE CİHAZLAR", accountCode: "253"},
    "II.D.5.": {name: "TAŞITLAR", accountCode: "254"},
    "II.D.6.": {name: "DEMİRBAŞLAR", accountCode: "255"},
    "II.D.7.": {name: "DİĞER MADDİ DURAN VARLIKLAR", accountCode: "256"},
    "II.D.8.": {name: "BİRİKMİŞ AMORTİSMANLAR (-)", accountCode: "257"},
    "II.D.9.": {name: "YAPILMAKTA OLAN YATIRIMLAR", accountCode: "258"},
    "II.D.10.": {name: "VERİLEN AVANSLAR", accountCode: "259"},
    "II.E.": {name: "MADDİ OLMAYAN DURAN VARLIKLAR", accountCode: "26"},
    "II.E.1.": {name: "HAKLAR", accountCode: "260"},
    "II.E.2.": {name: "ŞEREFİYE", accountCode: "261"},
    "II.E.3.": {name: "KURULUŞ VE ÖRGÜTLENME GİDERLERİ", accountCode: "262"},
    "II.E.4.": {name: "ARAŞTIRMA VE GELİŞTİRME GİDERLERİ", accountCode: "263"},
    "II.E.5.": {name: "ÖZEL MALİYETLER", accountCode: "264"},
    "II.E.6.": {name: "DİĞER MADDİ OLMAYAN DURAN VARLIKLAR", accountCode: "267"},
    "II.E.7.": {name: "BİRİKMİŞ AMORTİSMANLAR (-)", accountCode: "268"},
    "II.E.8.": {name: "VERİLEN AVANSLAR", accountCode: "269"},
    "II.F.": {name: "ÖZEL TÜKENMEYE TABİ VARLIKLAR", accountCode: "27"},
    "II.F.1.": {name: "ARAMA GİDERLERİ", accountCode: "271"},
    "II.F.2.": {name: "HAZIRLIK VE GELİŞTİRME GİDERLERİ", accountCode: "272"},
    "II.F.3.": {name: "DİĞER ÖZEL TÜKENMEYE TABİ VARLIKLAR", accountCode: "277"},
    "II.F.4.": {name: "BİRİKMİŞ TÜKENME PAYLARI (-)", accountCode: "278"},
    "II.F.9.": {name: "VERİLEN AVANSLAR", accountCode: "279"},
    "II.G.": {name: "GELECEK YILLARA AİT GİDERLER VE GELİR TAHAKKUKLARI", accountCode: "28"},
    "II.G.1.": {name: "GELECEK YILLARA AİT GİDERLER", accountCode: "280"},
    "II.G.2.": {name: "GELİR TAHAKKUKLARI", accountCode: "281"},
    "II.H.": {name: "DİĞER DURAN VARLIKLAR", accountCode: "29"},
    "II.H.1.": {name: "GELECEK YILLARDA İNDİRİLECEK KATMA DEĞER VERGİSİ", accountCode: "291"},
    "II.H.2.": {name: "DİĞER KATMA DEĞER VERGİSİ", accountCode: "292"},
    "II.H.3.": {name: "GELECEK YILLAR İHTİYACI STOKLAR", accountCode: "293"},
    "II.H.4.": {name: "ELDEN ÇIKARILACAK STOKLAR VE MADDİ DURAN VARLIKLAR", accountCode: "294"},
    "II.H.5.": {name: "DİĞER ÇEŞİTLİ DURAN VARLIKLAR", accountCode: "297"},
    "II.H.6.": {name: "STOK DEĞER DÜŞÜKLÜĞÜ KARŞILIĞI (-)", accountCode: "298"},
    "II.H.7.": {name: "BİRİKMİŞ AMORTİSMANLAR (-)", accountCode: "299"},
    "III.": {name: "KISA VADELİ YABANCI KAYNAKLAR", accountCode: "3"},
    "III.A.": {name: "MALİ BORÇLAR", accountCode: "30"},
    "III.A.1.": {name: "BANKA KREDİLERİ", accountCode: "300"},
    "III.A.2.": {name: "UZUN VADELİ KREDİLERİN ANAPARA TAKSİTLERİ VE FAİZLERİ", accountCode: "303"},
    "III.A.3.": {name: "TAHVİL ANAPARA BORÇ, TAKSİT VE FAİZLERİ", accountCode: "304"},
    "III.A.4.": {name: "ÇIKARILMIŞ BONOLAR VE SENETLER", accountCode: "305"},
    "III.A.5.": {name: "ÇIKARILMIŞ DİĞER MENKUL KIYMETLER", accountCode: "306"},
    "III.A.6.": {name: "MENKUL KIYMETLER İHRAÇ FARKI (-)", accountCode: "308"},
    "III.A.7.": {name: "DİĞER MALİ BORÇLAR", accountCode: "309"},
    "III.B.": {name: "TİCARİ BORÇLAR", accountCode: "32"},
    "III.B.1.": {name: "SATICILAR", accountCode: "320"},
    "III.B.2.": {name: "BORÇ SENETLERİ", accountCode: "321"},
    "III.B.3.": {name: "BORÇ SENETLERİ REESKONTU (-)", accountCode: "322"},
    "III.B.4.": {name: "ALINAN DEPOZİTO VE TEMİNATLAR", accountCode: "326"},
    "III.B.5.": {name: "DİĞER TİCARİ BORÇLAR", accountCode: "329"},
    "III.C.": {name: "DİĞER BORÇLAR", accountCode: "33"},
    "III.C.1.": {name: "ORTAKLARA BORÇLAR", accountCode: "331"},
    "III.C.2.": {name: "İŞTİRAKLERE BORÇLAR", accountCode: "332"},
    "III.C.3.": {name: "BAĞLI ORTAKLIKLARA BORÇLAR", accountCode: "333"},
    "III.C.4.": {name: "PERSONELE BORÇLAR", accountCode: "335"},
    "III.C.5.": {name: "DİĞER BORÇ SENETLERİ REESKONTU (-)", accountCode: "337"},
    "III.C.6.": {name: "DİĞER ÇEŞİTLİ BORÇLAR(1)", accountCode: "339"},
    "III.D.": {name: "ALINAN AVANSLAR", accountCode: "34"},
    "III.D.1.": {name: "ALINAN SİPARİŞ AVANSLARI", accountCode: "340"},
    "III.D.2.": {name: "ALINAN DİĞER AVANSLAR", accountCode: "349"},
    "III.F.": {name: "ÖDENECEK VERGİ VE DİĞER YÜKÜMLÜLÜKLER", accountCode: "36"},
    "III.F.1.": {name: "ÖDENECEK VERGİ VE FONLAR", accountCode: "360"},
    "III.F.2.": {name: "ÖDENECEK SOSYAL GÜVENLİK KESİNTİLERİ", accountCode: "361"},
    "III.F.3.": {name: "VADESİ GEÇMİŞ ERTELENMİŞ VEYA TAKSİTLENDİRİLMİŞ VERGİ VE DİĞER YÜKÜMLÜLÜKLER", accountCode: "368"},
    "III.F.4.": {name: "ÖDENECEK DİĞER YÜKÜMLÜLÜKLER", accountCode: "369"},
    "III.G.": {name: "BORÇ VE GİDER KARŞILIKLARI", accountCode: "37"},
    "III.G.1.": {name: "DÖNEM KARI VERGİ VE DİĞER YASAL YÜKÜMLÜLÜK KARŞILIKLARI", accountCode: "370"},
    "III.G.2.": {name: "DÖNEM KARININ PEŞİN ÖDENEN VERGİ VE DİĞER YÜKÜMLÜLÜKLERİ (-)", accountCode: "371"},
    "III.G.3.": {name: "KIDEM TAZMİNATI KARŞILIĞI", accountCode: "372"},
    "III.G.4.": {name: "MALİYET GİDERLERİ KARŞILIĞI", accountCode: "373"},
    "III.G.5.": {name: "DİĞER BORÇ VE GİDER KARŞILIKLARI", accountCode: "379"},
    "III.H.": {name: "GELECEK AYLARA AİT GELİRLER VE GİDER TAHAKKUKLARI", accountCode: "38"},
    "III.H.1.": {name: "GELECEK AYLARA AİT GELİRLER", accountCode: "380"},
    "III.H.2.": {name: "GİDER TAHAKKUKLARI", accountCode: "381"},
    "III.I.": {name: "DİĞER KISA VADELİ YABANCI KAYNAKLAR", accountCode: "39"},
    "III.I.1.": {name: "HESAPLANAN KDV", accountCode: "391"},
    "III.I.2.": {name: "DİĞER KDV", accountCode: "392"},
    "III.I.3.": {name: "SAYIM VE TESELLÜM FAZLALARI(1)", accountCode: "398"},
    "III.I.4.": {name: "DİĞER ÇEŞİTLİ YABANCI KAYNAKLAR", accountCode: "399"},
    "IV.": {name: "UZUN VADELİ YABANCI KAYNAKLAR", accountCode: "4"},
    "IV.A.": {name: "MALİ BORÇLAR", accountCode: "40"},
    "IV.A.1.": {name: "BANKA KREDİLERİ", accountCode: "400"},
    "IV.A.2.": {name: "ÇIKARILMIŞ TAHVİLLER", accountCode: "405"},
    "IV.A.3.": {name: "ÇIKARILMIŞ DİĞER MENKUL KIYMETLER", accountCode: "407"},
    "IV.A.4.": {name: "MENKUL KIYMETLER İHRAÇ FARKI (-)", accountCode: "408"},
    "IV.A.5.": {name: "DİĞER MALİ BORÇLAR", accountCode: "409"},
    "IV.B.": {name: "TİCARİ BORÇLAR", accountCode: "42"},
    "IV.B.0.": {name: "SATICILAR", accountCode: "420"},
    "IV.B.1.": {name: "BORÇ SENETLERİ", accountCode: "421"},
    "IV.B.2.": {name: "BORÇ SENETLERİ REESKONTU (-)", accountCode: "422"},
    "IV.B.6.": {name: "ALINAN DEPOZİTO VE TEMİNATLAR", accountCode: "426"},
    "IV.B.9.": {name: "DİĞER TİCARİ BORÇLAR", accountCode: "429"},
    "IV.C.": {name: "DİĞER BORÇLAR", accountCode: "43"},
    "IV.C.1.": {name: "ORTAKLARA BORÇLAR", accountCode: "431"},
    "IV.C.2.": {name: "İŞTİRAKLERE BORÇLAR", accountCode: "432"},
    "IV.C.3.": {name: "BAĞLI ORTAKLIKLARA BORÇLAR", accountCode: "433"},
    "IV.C.7.": {name: "DİĞER BORÇ SENETLERİ REESKONTU (-)", accountCode: "437"},
    "IV.C.8.": {name: "KAMUYA OLAN ERTELENMİŞ VEYA TAKSİTLENDİRİLMİŞ BORÇLAR", accountCode: "438"},
    "IV.C.9.": {name: "DİĞER ÇEŞİTLİ BORÇLAR(1)", accountCode: "439"},
    "IV.D.": {name: "ALINAN AVANSLAR", accountCode: "44"},
    "IV.D.0.": {name: "ALINAN SİPARİŞ AVANSLARI", accountCode: "440"},
    "IV.D.9.": {name: "ALINAN DİĞER AVANSLAR", accountCode: "449"},
    "IV.E.": {name: "BORÇ VE GİDER KARŞILIKLARI", accountCode: "47"},
    "IV.E.2.": {name: "KIDEM TAZMİNATI KARŞILIĞI", accountCode: "472"},
    "IV.E.9.": {name: "DİĞER BORÇ VE GİDER KARŞILIKLARI", accountCode: "479"},
    "IV.F.": {name: "GELECEK YILLARA AİT GELİRLER VE GİDER TAHAKKUKLARI", accountCode: "48"},
    "IV.F.0.": {name: "GELECEK YILLARA AİT GELİRLER", accountCode: "480"},
    "IV.F.1.": {name: "GİDER TAHAKKUKLARI", accountCode: "481"},
    "IV.G.": {name: "DİĞER UZUN VADELİ YABANCI KAYNAKLAR", accountCode: "49"},
    "IV.G.2.": {name: "GELECEK YILLARA ERTELENEN VEYA TERKİN EDİLEN KATMA DEĞER VERGİSİ(1)", accountCode: "492"},
    "IV.G.3.": {name: "TESİSE KATILMA PAYLARI", accountCode: "493"},
    "IV.G.9.": {name: "DİĞER ÇEŞİTLİ UZUN VADELİ YABANCI KAYNAKLAR", accountCode: "499"},
    "V.": {name: "ÖZ KAYNAKLAR", accountCode: "5"},
    "V.A.": {name: "ÖDENMİŞ SERMAYE", accountCode: "50"},
    "V.A.1.": {name: "SERMAYE", accountCode: "500"},
    "V.A.2.": {name: "ÖDENMEMİŞ SERMAYE (-)", accountCode: "501"},
    "V.B.": {name: "SERMAYE YEDEKLERİ", accountCode: "52"},
    "V.B.1.": {name: "HİSSE SENETLERİ İHRAÇ PRİMLERİ", accountCode: "520"},
    "V.B.2.": {name: "HİSSE SENEDİ İPTAL KARLARI", accountCode: "521"},
    "V.B.3.": {name: "M.D.V. YENİDEN DEĞERLEME ARTIŞLARI", accountCode: "522"},
    "V.B.4.": {name: "İŞTİRAKLER YENİDEN DEĞERLEME ARTIŞLARI", accountCode: "523"},
    "V.B.5.": {name: "DİĞER SERMAYE YEDEKLERİ", accountCode: "529"},
    "V.C.": {name: "KAR YEDEKLERİ", accountCode: "54"},
    "V.C.1.": {name: "YASAL YEDEKLER", accountCode: "540"},
    "V.C.2.": {name: "STATÜ YEDEKLERİ", accountCode: "541"},
    "V.C.3.": {name: "OLAĞANÜSTÜ YEDEKLER", accountCode: "542"},
    "V.C.4.": {name: "DİĞER KAR YEDEKLERİ", accountCode: "548"},
    "V.C.5.": {name: "ÖZEL FONLAR", accountCode: "549"},
    "V.D.": {name: "GEÇMİŞ YILLAR KARLARI", accountCode: "57"},
    "V.D.1.": {name: "GEÇMİŞ YILLAR KARLARI", accountCode: "570"},
    "V.E.": {name: "GEÇMİŞ YILLAR ZARARLARI (-)", accountCode: "58"},
    "V.E.1.": {name: "GEÇMİŞ YILLAR ZARARLARI", accountCode: "580"},
    "V.F.": {name: "DÖNEM NET KARI (ZARARI)", accountCode: "59"},
    "V.F.1.": {name: "DÖNEM NET KARI", accountCode: "590"},
    "V.F.2.": {name: "DÖNEM NET ZARARI (-)", accountCode: "591"},
    "VI.": {name: "GELİR TABLOSU HESAPLARI", accountCode: "6"},
    "VI.A.": {name: "BRÜT SATIŞLAR", accountCode: "60"},
    "VI.A.1.": {name: "YURTİÇİ SATIŞLAR", accountCode: "600"},
    "VI.A.2.": {name: "YURTDIŞI SATIŞLAR", accountCode: "601"},
    "VI.A.3.": {name: "DİĞER GELİRLER", accountCode: "602"},
    "VI.B.": {name: "SATIŞ İNDİRİMLERİ (-)", accountCode: "61"},
    "VI.B.1.": {name: "SATIŞTAN İADELER (-)", accountCode: "610"},
    "VI.B.2.": {name: "SATIŞ İSKONTOLARI (-)", accountCode: "611"},
    "VI.B.3.": {name: "DİĞER İNDİRİMLER (-)", accountCode: "612"},
    "VI.C.": {name: "NET SATIŞLAR", accountCode: "NET_SALES"},
    "VI.D.": {name: "SATIŞLARIN MALİYETİ (-)", accountCode: "62"},
    "VI.D.1.": {name: "SATILAN MAMÜLLER MALİYETİ (-)", accountCode: "620"},
    "VI.D.2.": {name: "SATILAN TİCARİ MALLAR MALİYETİ (-)", accountCode: "621"},
    "VI.D.3.": {name: "SATILAN HİZMET MALİYETİ (-)", accountCode: "622"},
    "VI.D.4.": {name: "DİĞER SATIŞLARIN MALİYETİ (-)", accountCode: "623"},
    "VI.E.": {name: "FAALİYET GİDERLERİ (-)", accountCode: "63"},
    "VI.E.1.": {name: "ARAŞTIRMA VE GELİŞTİRME GİDERLERİ (-)", accountCode: "630"},
    "VI.E.2.": {name: "PAZARLAMA SATIŞ VE DAĞITIM GİDERLERİ", accountCode: "631"},
    "VI.E.3.": {name: "GENEL YÖNETİM GİDERLERİ (-)", accountCode: "632"},
    "VI.F.": {name: "DİĞER FAALİYETLERDEN OLAĞAN GELİR VE KARLAR", accountCode: "64"},
    "VI.F.1.": {name: "İŞTİRAKLERDEN TEMETTÜ GELİRLERİ", accountCode: "640"},
    "VI.F.2.": {name: "BAĞLI ORTAKLIKLARDAN TEMETTÜ GELİRLERİ", accountCode: "641"},
    "VI.F.3.": {name: "FAİZ GELİRLERİ", accountCode: "642"},
    "VI.F.4.": {name: "KOMİSYON GELİRLERİ", accountCode: "643"},
    "VI.F.5.": {name: "KONUSU KALMAYAN KARŞILIKLAR", accountCode: "644"},
    "VI.F.6.": {name: "MENKUL KIYMET SATIŞ KARLARI", accountCode: "645"},
    "VI.F.7.": {name: "KAMBİYO KARLARI", accountCode: "646"},
    "VI.F.8.": {name: "REESKONT FAİZ GELİRLERİ", accountCode: "647"},
    "VI.F.9.": {name: "ENFLASYON DÜZELTMESİ KARLARI", accountCode: "648"},
    "VI.F.10.": {name: "FAALİYETLE İLGİLİ DİĞER GELİR VE KARLAR", accountCode: "649"},
    "VI.G.": {name: "DİĞER FAALİYETLERDEN OLAĞAN GİDER VE ZARARLAR (-)", accountCode: "65"},
    "VI.G.1.": {name: "KOMİSYON GİDERLERİ (-)", accountCode: "653"},
    "VI.G.2.": {name: "KARŞILIK GİDERLERİ (-)", accountCode: "654"},
    "VI.G.3.": {name: "MENKUL KIYMET SATIŞ ZARARLARI (-)", accountCode: "655"},
    "VI.G.4.": {name: "KAMBİYO ZARARLARI (-)", accountCode: "656"},
    "VI.G.5.": {name: "REESKONT FAİZ GİDERLERİ (-)", accountCode: "657"},
    "VI.G.6.": {name: "ENFLASYON DÜZELTMESİ ZARARLARI (-)", accountCode: "658"},
    "VI.G.7.": {name: "DİĞER OLAĞAN GİDER VE ZARARLAR (-)", accountCode: "659"},
    "VI.H.": {name: "FİNANSMAN GİDERLERİ (-)", accountCode: "66"},
    "VI.H.1.": {name: "KISA VADELİ BORÇLANMA GİDERLERİ (-)", accountCode: "660"},
    "VI.H.2.": {name: "UZUN VADELİ BORÇLANMA GİDERLERİ (-)", accountCode: "661"},
    "VI.I.": {name: "OLAĞANDIŞI GELİR VE KARLAR", accountCode: "67"},
    "VI.I.1.": {name: "ÖNCEKİ DÖNEM GELİR VE KARLARI", accountCode: "671"},
    "VI.I.2.": {name: "DİĞER OLAĞANDIŞI GELİR VE KARLAR", accountCode: "679"},
    "VI.J.": {name: "OLAĞANDIŞI GİDER VE ZARARLAR (-)", accountCode: "68"},
    "VI.J.1.": {name: "ÇALIŞMAYAN KISIM GİDER VE ZARARLARI (-)", accountCode: "680"},
    "VI.J.2.": {name: "ÖNCEKİ DÖNEM GİDER VE ZARARLARI (-)", accountCode: "681"},
    "VI.J.3.": {name: "DİĞER OLAĞANDIŞI GİDER VE ZARARLAR (-)", accountCode: "689"},
    "VI.K.": {name: "DÖNEM NET KARI (ZARARI)", accountCode: "69"},
    "VI.K.1.": {name: "DÖNEM KARI VEYA ZARARI", accountCode: "690"},
    "VI.K.2.": {name: "DÖNEM KARI VERGİ VE DİĞER YASAL YÜKÜMLÜLÜK KARŞILIKLARI (-)", accountCode: "691"},
    "VI.K.3.": {name: "DÖNEM NET KARI VEYA ZARARI", accountCode: "692"},
    "VI.K.4.": {name: "YILLARA YAYGIN İNŞAAT ENFLASYON DÜZELTME", accountCode: "697"},
    "VI.K.5.": {name: "ENFLASYON DÜZELTME", accountCode: "698"},
    "VII.": {name: "MALİYET HESAPLARI (7/A SEÇENEĞİ)", accountCode: "7"},
    "VII.A.": {name: "MALİYET MUHASEBESİ BAĞLANTI HESAPLARI", accountCode: "70"},
    "VII.A.1.": {name: "MALİYET MUHASEBESİ BAĞLANTI HESABI", accountCode: "700"},
    "VII.A.2.": {name: "MALİYET MUHASEBESİ YANSITMA HESABI", accountCode: "701"},
    "VII.B.": {name: "DİREKT İLKMADDE VE MALZEME GİDERLERİ", accountCode: "71"},
    "VII.B.1.": {name: "DİREKT İLKMADDE VE MALZEME GİDERLERİ", accountCode: "710"},
    "VII.B.2.": {name: "DİREKT İLKMADDE VE MALZEME YANSITMA HESABI", accountCode: "711"},
    "VII.B.3.": {name: "DİREKT İLKMADDE VE MALZEME FİYAT FARKI", accountCode: "712"},
    "VII.B.4.": {name: "DİREKT İLKMADDE VE MALZEME MİKTAR FARKI", accountCode: "713"},
    "VII.C.": {name: "DİREKT İŞÇİLİK GİDERLERİ", accountCode: "72"},
    "VII.C.1.": {name: "DİREKT İŞÇİLİK GİDERLERİ", accountCode: "720"},
    "VII.C.2.": {name: "DİREKT İŞCİLİK GİDERLERİ YANSITMA HESABI", accountCode: "721"},
    "VII.C.3.": {name: "DİREKT İŞÇİLİK ÜCRET FARKLARI", accountCode: "722"},
    "VII.C.4.": {name: "DİREKT İŞÇİLİK SÜRE (ZAMAN) FARKLARI", accountCode: "723"},
    "VII.D.": {name: "GENEL ÜRETİM GİDERLERİ", accountCode: "73"},
    "VII.D.1.": {name: "GENEL ÜRETİM GİDERLERİ", accountCode: "730"},
    "VII.D.2.": {name: "GENEL ÜRETİM GİDERLERİ YANSITMA HESABI", accountCode: "731"},
    "VII.D.3.": {name: "GENEL ÜRETİM GİDERLERİ BÜTÇE FARKLARI", accountCode: "732"},
    "VII.D.4.": {name: "GENEL ÜRETİM GİDERLERİ VERİMLİLİK FARKLARI", accountCode: "733"},
    "VII.D.5.": {name: "GENEL ÜRETİM GİDERLERİ KAPASİTE FARKLARI", accountCode: "734"},
    "VII.E.": {name: "HİZMET ÜRETİM MALİYETİ", accountCode: "74"},
    "VII.E.1.": {name: "HİZMET ÜRETİM MALİYETİ", accountCode: "740"},
    "VII.E.2.": {name: "HİZMET ÜRETİM MALİYETİ YANSITMA HESABI", accountCode: "741"},
    "VII.E.3.": {name: "HİZMET ÜRETİM MALİYETİ FARK HESAPLARI", accountCode: "742"},
    "VII.F.": {name: "ARAŞTIRMA VE GELİŞTİRME GİDERLERİ", accountCode: "75"},
    "VII.F.1.": {name: "ARAŞTIRMA VE GELİŞTİRME GİDERLERİ", accountCode: "750"},
    "VII.F.2.": {name: "ARAŞTIRMA VE GELİŞTİRME GİDERLERİ YANSITMA HESABI", accountCode: "751"},
    "VII.F.3.": {name: "ARAŞTIRMA VE GELİŞTİRME GİDER FARKLARI", accountCode: "752"},
    "VII.G.": {name: "PAZARLAMA SATIŞ YE DAĞITIM GİDERLERİ", accountCode: "76"},
    "VII.G.1.": {name: "PAZARLAMA SATIŞ VE DAĞITIM GİDERLERİ", accountCode: "760"},
    "VII.G.2.": {name: "PAZARLAMA SATIŞ VE DAĞITIM GİDERLERİ YANSITMA HESABI", accountCode: "761"},
    "VII.G.3.": {name: "PAZARLAMA SATIŞ VE DAĞITIM GİDERLERİ FARK HESABI", accountCode: "762"},
    "VII.H.": {name: "GENEL YÖNETİM GİDERLERİ", accountCode: "77"},
    "VII.H.1.": {name: "GENEL YÖNETİM GİDERLERİ", accountCode: "770"},
    "VII.H.2.": {name: "GENEL YÖNETİM GİDERLERİ YANSITMA HESABI", accountCode: "771"},
    "VII.H.3.": {name: "GENEL YÖNETİM GİDER FARKLARI HESABI", accountCode: "772"},
    "VII.I.": {name: "FİNANSMAN GİDERLERİ", accountCode: "78"},
    "VII.I.1.": {name: "FİNANSMAN GİDERLERİ", accountCode: "780"},
    "VII.I.2.": {name: "FİNANSMAN GİDERLERİ YANSITMA HESABI", accountCode: "781"},
    "VII.I.3.": {name: "FİNANSMAN GİDERLERİ FARK HESABI", accountCode: "782"},
    "VII.J.": {name: "GİDER ÇEŞİTLERİ (7/B SEÇENEĞİ)", accountCode: "79"},
    "VII.J.1.": {name: "İLKMADDE VE MALZEME GİDERLERİ", accountCode: "790"},
    "VII.J.2.": {name: "İŞÇİ ÜCRET VE GİDERLERİ", accountCode: "791"},
    "VII.J.3.": {name: "MEMUR ÜCRET VE GİDERLERİ", accountCode: "792"},
    "VII.J.4.": {name: "DIŞARIDAN SAĞLANAN FAYDA VE HİZMETLER", accountCode: "793"},
    "VII.J.5.": {name: "ÇEŞİTLİ GİDERLER", accountCode: "794"},
    "VII.J.6.": {name: "VERGİ, RESİM VE HARÇLAR", accountCode: "795"},
    "VII.J.7.": {name: "AMORTİSMANLAR VE TÜKENME PAYLARI", accountCode: "796"},
    "VII.J.8.": {name: "FİNANSMAN GİDERLERİ", accountCode: "797"},
    "VII.J.9.": {name: "GİDER ÇEŞİTLERİ YANSITMA HESABI", accountCode: "798"},
    "VII.J.10.": {name: "ÜRETİM MALİYET HESABI", accountCode: "799"},
    "VIII.": {name: "(SERBEST)", accountCode: "8"},
    "IX.": {name: "NAZIM HESAPLAR", accountCode: "9"},
    "X.": {name: "(SERBEST)", accountCode: "0"},
}

export let DefaultAccountCode = new Map<string, FinancialLineDTO>([
    ["1", new FinancialLineDTO("DÖNEN VARLIKLAR")],
    ["10", new FinancialLineDTO("HAZIR DEĞERLER", "1")],
    ["100", new FinancialLineDTO("KASA", "10")],
    ["101", new FinancialLineDTO("ALINAN ÇEKLER", "10")],
    ["102", new FinancialLineDTO("BANKALAR", "10")],
    ["103", new FinancialLineDTO("VERİLEN ÇEKLER VE ÖDEME EMİRLERİ (-)", "10", FinancialLineType.MINUS)],
    ["108", new FinancialLineDTO("DİĞER HAZIR DEĞERLER", "10")],
    ["11", new FinancialLineDTO("MENKUL KIYMETLER", "1")],
    ["110", new FinancialLineDTO("HİSSE SENETLERİ", "11")],
    ["111", new FinancialLineDTO("ÖZEL KESİM TAHVİL, SENET VE BONOLARI", "11")],
    ["112", new FinancialLineDTO("KAMU KESİMİ TAHVİL, SENET VE BONOLARI", "11")],
    ["118", new FinancialLineDTO("DİĞER MENKUL KIYMETLER", "11")],
    ["119", new FinancialLineDTO("MENKUL KIYMETLER DEĞER DÜŞÜKLÜĞÜ KARŞILIĞI (-)", "11", FinancialLineType.MINUS)],
    ["12", new FinancialLineDTO("TİCARİ ALACAKLAR", "1")],
    ["120", new FinancialLineDTO("ALICILAR", "12")],
    ["121", new FinancialLineDTO("ALACAK SENETLERİ", "12")],
    ["122", new FinancialLineDTO("ALACAK SENETLERİ REESKONTU (-)", "12", FinancialLineType.MINUS)],
    ["126", new FinancialLineDTO("VERİLEN DEPOZİTO VE TEMİNATLAR", "12")],
    ["128", new FinancialLineDTO("ŞÜPHELİ TİCARİ ALACAKLAR", "12")],
    ["129", new FinancialLineDTO("ŞÜPHELİ TİCARİ ALACAKLAR KARŞILIĞI (-)", "12", FinancialLineType.MINUS)],
    ["13", new FinancialLineDTO("DİĞER ALACAKLAR", "1")],
    ["131", new FinancialLineDTO("ORTAKLARDAN ALACAKLAR", "13")],
    ["132", new FinancialLineDTO("İŞTİRAKLERDEN ALACAKLAR", "13")],
    ["133", new FinancialLineDTO("BAĞLI ORTAKLIKLARDAN ALACAKLAR", "13")],
    ["135", new FinancialLineDTO("PERSONELDEN ALACAKLAR", "13")],
    ["136", new FinancialLineDTO("DİĞER ÇEŞİTLİ ALACAKLAR", "13")],
    ["137", new FinancialLineDTO("DİĞER ALACAK SENETLERİ REESKONTU (-)", "13", FinancialLineType.MINUS)],
    ["138", new FinancialLineDTO("ŞÜPHELİ DİĞER ALACAKLAR", "13")],
    ["139", new FinancialLineDTO("ŞÜPHELİ DİĞER ALACAKLAR KARŞILIĞI (-)", "13", FinancialLineType.MINUS)],
    ["15", new FinancialLineDTO("STOKLAR", "1")],
    ["150", new FinancialLineDTO("İLK MADDE VE MALZEME", "15")],
    ["151", new FinancialLineDTO("YARI MAMULLER - ÜRETİM", "15")],
    ["152", new FinancialLineDTO("MAMÜLLER", "15")],
    ["153", new FinancialLineDTO("TİCARİ MALLAR", "15")],
    ["157", new FinancialLineDTO("DİĞER STOKLAR", "15")],
    ["158", new FinancialLineDTO("STOK DEĞER DÜŞÜKLÜĞÜ KARŞILIĞI (-)", "15", FinancialLineType.MINUS)],
    ["159", new FinancialLineDTO("VERİLEN SİPARİŞ AVANSLARI", "15")],
    ["18", new FinancialLineDTO("GELECEK AYLARA AİT GİDERLER VE GELİR TAHAKKUKLARI", "1")],
    ["180", new FinancialLineDTO("GELECEK AYLARA AİT GİDERLER", "18")],
    ["181", new FinancialLineDTO("GELİR TAHAKKUKLARI", "18")],
    ["19", new FinancialLineDTO("DİĞER DÖNEN VARLIKLAR", "1")],
    ["191", new FinancialLineDTO("İNDİRİLECEK KATMA DEĞER VERGİSİ", "19")],
    ["192", new FinancialLineDTO("DİĞER KATMA DEĞER VERGİSİ", "19")],
    ["193", new FinancialLineDTO("PEŞİN ÖDENEN VERGİLER VE FONLAR", "19")],
    ["196", new FinancialLineDTO("PERSONEL AVANSLARI", "19")],
    ["197", new FinancialLineDTO("SAYIM VE TESELLÜM NOKSANLARI", "19")],
    ["198", new FinancialLineDTO("DİĞER ÇEŞİTLİ DÖNEN VARLIKLAR", "19")],
    ["199", new FinancialLineDTO("DİĞER DÖNEN VARLIKLAR KARŞILIĞI (-)", "19", FinancialLineType.MINUS)],
    ["2", new FinancialLineDTO("DURAN VARLIKLAR")],
    ["22", new FinancialLineDTO("TİCARİ ALACAKLAR", "2")],
    ["220", new FinancialLineDTO("ALICILAR", "22")],
    ["221", new FinancialLineDTO("ALACAK SENETLERİ", "22")],
    ["222", new FinancialLineDTO("ALACAK SENETLERİ REESKONTU (-)", "22", FinancialLineType.MINUS)],
    ["226", new FinancialLineDTO("VERİLEN DEPOZİTO VE TEMİNATLAR", "22")],
    ["229", new FinancialLineDTO("ŞÜPHELİ ALACAKLAR KARŞILIĞI (-)", "22", FinancialLineType.MINUS)],
    ["23", new FinancialLineDTO("DİĞER ALACAKLAR (1)", "2")],
    ["230", new FinancialLineDTO("ORTAKLARDAN ALACAKLAR", "23")],
    ["231", new FinancialLineDTO("İŞTİRAKLERDEN ALACAKLAR", "23")],
    ["232", new FinancialLineDTO("BAĞLI ORTAKLIKLARDAN ALACAKLAR", "23")],
    ["235", new FinancialLineDTO("PERSONELDEN ALACAKLAR", "23")],
    ["236", new FinancialLineDTO("DİĞER ÇEŞİTLİ ALACAKLAR", "23")],
    ["237", new FinancialLineDTO("DİĞER ALACAK SENETLERİ REESKONTU (-)", "23", FinancialLineType.MINUS)],
    ["239", new FinancialLineDTO("ŞÜPHELİ DİĞER ALACAKLAR KARŞILIĞI (-)", "23", FinancialLineType.MINUS)],
    ["24", new FinancialLineDTO("MALİ DURAN VARLIKLAR", "2")],
    ["240", new FinancialLineDTO("BAĞLI MENKUL KIYMETLER", "24")],
    ["241", new FinancialLineDTO("BAĞLI MENKUL KIYMETLER DEĞER DÜŞÜKLÜĞÜ KARŞILIĞI (-)", "24", FinancialLineType.MINUS)],
    ["242", new FinancialLineDTO("İŞTİRAKLER", "24")],
    ["243", new FinancialLineDTO("İŞTİRAKLERE SERMAYE TAAHHÜTLERİ (-)", "24")],
    ["244", new FinancialLineDTO("İŞTİRAKLER SERMAYE PAYLARI DEĞER DÜŞÜKLÜĞÜ KARŞILIĞI (-)", "24", FinancialLineType.MINUS)],
    ["245", new FinancialLineDTO("BAĞLI ORTAKLIKLAR", "24")],
    ["246", new FinancialLineDTO("BAĞLI ORTAKLIKLARA SERMAYE TAAHHÜTLERİ (-)", "24")],
    ["247", new FinancialLineDTO("BAĞLI ORTAKLIKLAR SERMAYE PAYLARI DEĞER DÜŞÜKLÜGÜ KARŞILIĞI (-)", "24", FinancialLineType.MINUS)],
    ["248", new FinancialLineDTO("DİĞER MALİ DURAN VARLIKLAR", "24")],
    ["249", new FinancialLineDTO("DİĞER MALİ DURAN VARLIKLAR KARŞILIĞI (-)", "24", FinancialLineType.MINUS)],
    ["25", new FinancialLineDTO("MADDİ DURAN VARLIKLAR", "2")],
    ["250", new FinancialLineDTO("ARAZİ VE ARSALAR", "25")],
    ["251", new FinancialLineDTO("YER ALTI VE YER ÜSTÜ DÜZENLERİ", "25")],
    ["252", new FinancialLineDTO("BİNALAR", "25")],
    ["253", new FinancialLineDTO("TESİS, MAKİNE VE CİHAZLAR", "25")],
    ["254", new FinancialLineDTO("TAŞITLAR", "25")],
    ["255", new FinancialLineDTO("DEMİRBAŞLAR", "25")],
    ["256", new FinancialLineDTO("DİĞER MADDİ DURAN VARLIKLAR", "25")],
    ["257", new FinancialLineDTO("BİRİKMİŞ AMORTİSMANLAR (-)", "25", FinancialLineType.MINUS)],
    ["258", new FinancialLineDTO("YAPILMAKTA OLAN YATIRIMLAR", "25")],
    ["259", new FinancialLineDTO("VERİLEN AVANSLAR", "25")],
    ["26", new FinancialLineDTO("MADDİ OLMAYAN DURAN VARLIKLAR", "2")],
    ["260", new FinancialLineDTO("HAKLAR", "26")],
    ["261", new FinancialLineDTO("ŞEREFİYE", "26")],
    ["262", new FinancialLineDTO("KURULUŞ VE ÖRGÜTLENME GİDERLERİ", "26")],
    ["263", new FinancialLineDTO("ARAŞTIRMA VE GELİŞTİRME GİDERLERİ", "26")],
    ["264", new FinancialLineDTO("ÖZEL MALİYETLER", "26")],
    ["267", new FinancialLineDTO("DİĞER MADDİ OLMAYAN DURAN VARLIKLAR", "26")],
    ["268", new FinancialLineDTO("BİRİKMİŞ AMORTİSMANLAR (-)", "26", FinancialLineType.MINUS)],
    ["269", new FinancialLineDTO("VERİLEN AVANSLAR", "26")],
    ["27", new FinancialLineDTO("ÖZEL TÜKENMEYE TABİ VARLIKLAR", "2")],
    ["271", new FinancialLineDTO("ARAMA GİDERLERİ", "27")],
    ["272", new FinancialLineDTO("HAZIRLIK VE GELİŞTİRME GİDERLERİ", "27")],
    ["277", new FinancialLineDTO("DİĞER ÖZEL TÜKENMEYE TABİ VARLIKLAR", "27")],
    ["278", new FinancialLineDTO("BİRİKMİŞ TÜKENME PAYLARI (-)", "27", FinancialLineType.MINUS)],
    ["279", new FinancialLineDTO("VERİLEN AVANSLAR", "27")],
    ["28", new FinancialLineDTO("GELECEK YILLARA AİT GİDERLER VE GELİR TAHAKKUKLARI", "2")],
    ["280", new FinancialLineDTO("GELECEK YILLARA AİT GİDERLER", "28")],
    ["281", new FinancialLineDTO("GELİR TAHAKKUKLARI", "28")],
    ["29", new FinancialLineDTO("DİĞER DURAN VARLIKLAR", "2")],
    ["291", new FinancialLineDTO("GELECEK YILLARDA İNDİRİLECEK KATMA DEĞER VERGİSİ", "29")],
    ["292", new FinancialLineDTO("DİĞER KATMA DEĞER VERGİSİ", "29")],
    ["293", new FinancialLineDTO("GELECEK YILLAR İHTİYACI STOKLAR", "29")],
    ["294", new FinancialLineDTO("ELDEN ÇIKARILACAK STOKLAR VE MADDİ DURAN VARLIKLAR", "29")],
    ["297", new FinancialLineDTO("DİĞER ÇEŞİTLİ DURAN VARLIKLAR", "29")],
    ["298", new FinancialLineDTO("STOK DEĞER DÜŞÜKLÜĞÜ KARŞILIĞI (-)", "29", FinancialLineType.MINUS)],
    ["299", new FinancialLineDTO("BİRİKMİŞ AMORTİSMANLAR (-)", "29", FinancialLineType.MINUS)],
    ["3", new FinancialLineDTO("KISA VADELİ YABANCI KAYNAKLAR")],
    ["30", new FinancialLineDTO("MALİ BORÇLAR", "3")],
    ["300", new FinancialLineDTO("BANKA KREDİLERİ", "30")],
    ["303", new FinancialLineDTO("UZUN VADELİ KREDİLERİN ANAPARA TAKSİTLERİ VE FAİZLERİ", "30")],
    ["304", new FinancialLineDTO("TAHVİL ANAPARA BORÇ, TAKSİT VE FAİZLERİ", "30")],
    ["305", new FinancialLineDTO("ÇIKARILMIŞ BONOLAR VE SENETLER", "30")],
    ["306", new FinancialLineDTO("ÇIKARILMIŞ DİĞER MENKUL KIYMETLER", "30")],
    ["308", new FinancialLineDTO("MENKUL KIYMETLER İHRAÇ FARKI (-)", "30", FinancialLineType.MINUS)],
    ["309", new FinancialLineDTO("DİĞER MALİ BORÇLAR", "30")],
    ["32", new FinancialLineDTO("TİCARİ BORÇLAR", "3")],
    ["320", new FinancialLineDTO("SATICILAR", "32")],
    ["321", new FinancialLineDTO("BORÇ SENETLERİ", "32")],
    ["322", new FinancialLineDTO("BORÇ SENETLERİ REESKONTU (-)", "32", FinancialLineType.MINUS)],
    ["326", new FinancialLineDTO("ALINAN DEPOZİTO VE TEMİNATLAR", "32")],
    ["329", new FinancialLineDTO("DİĞER TİCARİ BORÇLAR", "32")],
    ["33", new FinancialLineDTO("DİĞER BORÇLAR", "3")],
    ["331", new FinancialLineDTO("ORTAKLARA BORÇLAR", "33")],
    ["332", new FinancialLineDTO("İŞTİRAKLERE BORÇLAR", "33")],
    ["333", new FinancialLineDTO("BAĞLI ORTAKLIKLARA BORÇLAR", "33")],
    ["335", new FinancialLineDTO("PERSONELE BORÇLAR", "33")],
    ["337", new FinancialLineDTO("DİĞER BORÇ SENETLERİ REESKONTU (-)", "33", FinancialLineType.MINUS)],
    ["339", new FinancialLineDTO("DİĞER ÇEŞİTLİ BORÇLAR(1)", "33")],
    ["34", new FinancialLineDTO("ALINAN AVANSLAR", "3")],
    ["340", new FinancialLineDTO("ALINAN SİPARİŞ AVANSLARI", "34")],
    ["349", new FinancialLineDTO("ALINAN DİĞER AVANSLAR", "34")],
    ["36", new FinancialLineDTO("ÖDENECEK VERGİ VE DİĞER YÜKÜMLÜLÜKLER", "3")],
    ["360", new FinancialLineDTO("ÖDENECEK VERGİ VE FONLAR", "36")],
    ["361", new FinancialLineDTO("ÖDENECEK SOSYAL GÜVENLİK KESİNTİLERİ", "36")],
    ["368", new FinancialLineDTO("VADESİ GEÇMİŞ ERTELENMİŞ VEYA TAKSİTLENDİRİLMİŞ VERGİ VE DİĞER YÜKÜMLÜLÜKLER", "36")],
    ["369", new FinancialLineDTO("ÖDENECEK DİĞER YÜKÜMLÜLÜKLER", "36")],
    ["37", new FinancialLineDTO("BORÇ VE GİDER KARŞILIKLARI", "3")],
    ["370", new FinancialLineDTO("DÖNEM KÂRI VERGİ VE DİĞER YASAL YÜKÜMLÜLÜK KARŞILIKLARI", "37")],
    ["371", new FinancialLineDTO("DÖNEM KÂRININ PEŞİN ÖDENEN VERGİ VE DİĞER YÜKÜMLÜLÜKLERİ (-)", "37", FinancialLineType.MINUS)],
    ["372", new FinancialLineDTO("KIDEM TAZMİNATI KARŞILIĞI", "37")],
    ["373", new FinancialLineDTO("MALİYET GİDERLERİ KARŞILIĞI", "37")],
    ["379", new FinancialLineDTO("DİĞER BORÇ VE GİDER KARŞILIKLARI", "37")],
    ["38", new FinancialLineDTO("GELECEK AYLARA AİT GELİRLER VE GİDER TAHAKKUKLARI", "3")],
    ["380", new FinancialLineDTO("GELECEK AYLARA AİT GELİRLER", "38")],
    ["381", new FinancialLineDTO("GİDER TAHAKKUKLARI", "38")],
    ["39", new FinancialLineDTO("DİĞER KISA VADELİ YABANCI KAYNAKLAR", "3")],
    ["391", new FinancialLineDTO("HESAPLANAN KDV", "39")],
    ["392", new FinancialLineDTO("DİĞER KDV", "39")],
    ["398", new FinancialLineDTO("SAYIM VE TESELLÜM FAZLALARI(1)", "39")],
    ["399", new FinancialLineDTO("DİĞER ÇEŞİTLİ YABANCI KAYNAKLAR", "39")],
    ["4", new FinancialLineDTO("UZUN VADELİ YABANCI KAYNAKLAR")],
    ["40", new FinancialLineDTO("MALİ BORÇLAR", "4")],
    ["400", new FinancialLineDTO("BANKA KREDİLERİ", "40")],
    ["405", new FinancialLineDTO("ÇIKARILMIŞ TAHVİLLER", "40")],
    ["407", new FinancialLineDTO("ÇIKARILMIŞ DİĞER MENKUL KIYMETLER", "40")],
    ["408", new FinancialLineDTO("MENKUL KIYMETLER İHRAÇ FARKI (-)", "40", FinancialLineType.MINUS)],
    ["409", new FinancialLineDTO("DİĞER MALİ BORÇLAR", "40")],
    ["42", new FinancialLineDTO("TİCARİ BORÇLAR", "4")],
    ["420", new FinancialLineDTO("SATICILAR", "42")],
    ["421", new FinancialLineDTO("BORÇ SENETLERİ", "42")],
    ["422", new FinancialLineDTO("BORÇ SENETLERİ REESKONTU (-)", "42", FinancialLineType.MINUS)],
    ["426", new FinancialLineDTO("ALINAN DEPOZİTO VE TEMİNATLAR", "42")],
    ["429", new FinancialLineDTO("DİĞER TİCARİ BORÇLAR", "42")],
    ["43", new FinancialLineDTO("DİĞER BORÇLAR", "4")],
    ["431", new FinancialLineDTO("ORTAKLARA BORÇLAR", "43")],
    ["432", new FinancialLineDTO("İŞTİRAKLERE BORÇLAR", "43")],
    ["433", new FinancialLineDTO("BAĞLI ORTAKLIKLARA BORÇLAR", "43")],
    ["437", new FinancialLineDTO("DİĞER BORÇ SENETLERİ REESKONTU (-)", "43", FinancialLineType.MINUS)],
    ["438", new FinancialLineDTO("KAMUYA OLAN ERTELENMİŞ VEYA TAKSİTLENDİRİLMİŞ BORÇLAR", "43")],
    ["439", new FinancialLineDTO("DİĞER ÇEŞİTLİ BORÇLAR(1)", "43")],
    ["44", new FinancialLineDTO("ALINAN AVANSLAR", "4")],
    ["440", new FinancialLineDTO("ALINAN SİPARİŞ AVANSLARI", "44")],
    ["449", new FinancialLineDTO("ALINAN DİĞER AVANSLAR", "44")],
    ["47", new FinancialLineDTO("BORÇ VE GİDER KARŞILIKLARI", "4")],
    ["472", new FinancialLineDTO("KIDEM TAZMİNATI KARŞILIĞI", "47")],
    ["479", new FinancialLineDTO("DİĞER BORÇ VE GİDER KARŞILIKLARI", "47")],
    ["48", new FinancialLineDTO("GELECEK YILLARA AİT GELİRLER VE GİDER TAHAKKUKLARI", "4")],
    ["480", new FinancialLineDTO("GELECEK YILLARA AİT GELİRLER", "48")],
    ["481", new FinancialLineDTO("GİDER TAHAKKUKLARI", "48")],
    ["49", new FinancialLineDTO("DİĞER UZUN VADELİ YABANCI KAYNAKLAR", "4")],
    ["492", new FinancialLineDTO("GELECEK YILLARA ERTELENEN VEYA TERKİN EDİLEN KATMA DEĞER VERGİSİ(1)", "49")],
    ["493", new FinancialLineDTO("TESİSE KATILMA PAYLARI", "49")],
    ["499", new FinancialLineDTO("DİĞER ÇEŞİTLİ UZUN VADELİ YABANCI KAYNAKLAR", "49")],
    ["5", new FinancialLineDTO("ÖZ KAYNAKLAR")],
    ["50", new FinancialLineDTO("ÖDENMİŞ SERMAYE", "5")],
    ["500", new FinancialLineDTO("SERMAYE", "50")],
    ["501", new FinancialLineDTO("ÖDENMEMİŞ SERMAYE (-)", "50", FinancialLineType.MINUS)],
    ["52", new FinancialLineDTO("SERMAYE YEDEKLERİ", "5")],
    ["520", new FinancialLineDTO("HİSSE SENETLERİ İHRAÇ PRİMLERİ", "52")],
    ["521", new FinancialLineDTO("HİSSE SENEDİ İPTAL KÂRLARI", "52")],
    ["522", new FinancialLineDTO("M.D.V. YENİDEN DEĞERLEME ARTIŞLARI", "52")],
    ["523", new FinancialLineDTO("İŞTİRAKLER YENİDEN DEĞERLEME ARTIŞLARI", "52")],
    ["529", new FinancialLineDTO("DİĞER SERMAYE YEDEKLERİ", "52")],
    ["54", new FinancialLineDTO("KÂR YEDEKLERİ", "5")],
    ["540", new FinancialLineDTO("YASAL YEDEKLER", "54")],
    ["541", new FinancialLineDTO("STATÜ YEDEKLERİ", "54")],
    ["542", new FinancialLineDTO("OLAĞANÜSTÜ YEDEKLER", "54")],
    ["548", new FinancialLineDTO("DİĞER KÂR YEDEKLERİ", "54")],
    ["549", new FinancialLineDTO("ÖZEL FONLAR", "54")],
    ["57", new FinancialLineDTO("GEÇMİŞ YILLAR KÂRLARI", "5")],
    ["570", new FinancialLineDTO("GEÇMİŞ YILLAR KÂRLARI", "57")],
    ["58", new FinancialLineDTO("GEÇMİŞ YILLAR ZARARLARI (-)", "5", FinancialLineType.MINUS)],
    ["580", new FinancialLineDTO("GEÇMİŞ YILLAR ZARARLARI", "58")],
    ["59", new FinancialLineDTO("DÖNEM NET KÂRI (ZARARI)", "5")],
    ["590", new FinancialLineDTO("DÖNEM NET KÂRI", "59")],
    ["591", new FinancialLineDTO("DÖNEM NET ZARARI (-)", "59", FinancialLineType.MINUS)],
    ["6", new FinancialLineDTO("GELİR TABLOSU HESAPLARI")],
    ["60", new FinancialLineDTO("BRÜT SATIŞLAR", "6")],
    ["600", new FinancialLineDTO("YURTİÇİ SATIŞLAR", "60")],
    ["601", new FinancialLineDTO("YURTDIŞI SATIŞLAR", "60")],
    ["602", new FinancialLineDTO("DİĞER GELİRLER", "60")],
    ["61", new FinancialLineDTO("SATIŞ İNDİRİMLERİ (-)", "6", FinancialLineType.MINUS)],
    ["610", new FinancialLineDTO("SATIŞTAN İADELER (-)", "61", FinancialLineType.MINUS)],
    ["611", new FinancialLineDTO("SATIŞ İSKONTOLARI (-)", "61", FinancialLineType.MINUS)],
    ["612", new FinancialLineDTO("DİĞER İNDİRİMLER (-)", "61", FinancialLineType.MINUS)],
    ["62", new FinancialLineDTO("SATIŞLARIN MALİYETİ (-)", "6", FinancialLineType.MINUS)],
    ["620", new FinancialLineDTO("SATILAN MAMÜLLER MALİYETİ (-)", "62", FinancialLineType.MINUS)],
    ["621", new FinancialLineDTO("SATILAN TİCARİ MALLAR MALİYETİ (-)", "62", FinancialLineType.MINUS)],
    ["622", new FinancialLineDTO("SATILAN HİZMET MALİYETİ (-)", "62", FinancialLineType.MINUS)],
    ["623", new FinancialLineDTO("DİĞER SATIŞLARIN MALİYETİ (-)", "62", FinancialLineType.MINUS)],
    ["63", new FinancialLineDTO("FAALİYET GİDERLERİ (-)", "6", FinancialLineType.MINUS)],
    ["630", new FinancialLineDTO("ARAŞTIRMA VE GELİŞTİRME GİDERLERİ (-)", "63", FinancialLineType.MINUS)],
    ["631", new FinancialLineDTO("PAZARLAMA SATIŞ VE DAĞITIM GİDERLERİ (-)", "63", FinancialLineType.MINUS)],
    ["632", new FinancialLineDTO("GENEL YÖNETİM GİDERLERİ (-)", "63", FinancialLineType.MINUS)],
    ["64", new FinancialLineDTO("DİĞER FAALİYETLERDEN OLAĞAN GELİR VE KÂRLAR", "6")],
    ["640", new FinancialLineDTO("İŞTİRAKLERDEN TEMETTÜ GELİRLERİ", "64")],
    ["641", new FinancialLineDTO("BAĞLI ORTAKLIKLARDAN TEMETTÜ GELİRLERİ", "64")],
    ["642", new FinancialLineDTO("FAİZ GELİRLERİ", "64")],
    ["643", new FinancialLineDTO("KOMİSYON GELİRLERİ", "64")],
    ["644", new FinancialLineDTO("KONUSU KALMAYAN KARŞILIKLAR", "64")],
    ["649", new FinancialLineDTO("FAALİYETLE İLGİLİ DİĞER GELİR VE KÂRLAR", "64")],
    ["65", new FinancialLineDTO("DİĞER FAALİYETLERDEN OLAĞAN GİDER VE ZARARLAR (-)", "6", FinancialLineType.MINUS)],
    ["652", new FinancialLineDTO("REESKONT FAİZ GİDERLERİ (-)(1)", "65", FinancialLineType.MINUS)],
    ["653", new FinancialLineDTO("KOMİSYON GİDERLERİ (-)", "65", FinancialLineType.MINUS)],
    ["654", new FinancialLineDTO("KARŞILIK GİDERLERİ (-)", "65", FinancialLineType.MINUS)],
    ["659", new FinancialLineDTO("DİĞER GİDER VE ZARARLAR (-)", "65", FinancialLineType.MINUS)],
    ["66", new FinancialLineDTO("FİNANSMAN GİDERLERİ (-)", "6", FinancialLineType.MINUS)],
    ["660", new FinancialLineDTO("KISA VADELİ BORÇLANMA GİDERLERİ (-)", "66", FinancialLineType.MINUS)],
    ["661", new FinancialLineDTO("UZUN VADELİ BORÇLANMA GİDERLERİ (-)", "66", FinancialLineType.MINUS)],
    ["67", new FinancialLineDTO("OLAĞANDIŞI GELİR VE KÂRLAR", "6")],
    ["671", new FinancialLineDTO("ÖNCEKİ DÖNEM GELİR VE KÂRLARI", "67")],
    ["679", new FinancialLineDTO("DİĞER OLAĞANDIŞI GELİR VE KÂRLAR", "67")],
    ["68", new FinancialLineDTO("OLAĞANDIŞI GİDER VE ZARARLAR (-)", "6", FinancialLineType.MINUS)],
    ["680", new FinancialLineDTO("ÇALIŞMAYAN KISIM GİDER VE ZARARLARI (-)", "68", FinancialLineType.MINUS)],
    ["681", new FinancialLineDTO("ÖNCEKİ DÖNEM GİDER VE ZARARLARI (-)", "68", FinancialLineType.MINUS)],
    ["689", new FinancialLineDTO("DİĞER OLAĞANDIŞI GİDER VE ZARARLAR (-)", "68", FinancialLineType.MINUS)],
    ["69", new FinancialLineDTO("DÖNEM NET KÂRI (ZARARI)", "6")],
    ["690", new FinancialLineDTO("DÖNEM KÂRI VEYA ZARARI", "69")],
    ["691", new FinancialLineDTO("DÖNEM KÂRI VERGİ VE DİĞER YASAL YÜKÜMLÜLÜK KARŞILIKLARI (-)", "69", FinancialLineType.MINUS)],
    ["692", new FinancialLineDTO("DÖNEM NET KÂRI VEYA ZARARI", "69")],
    ["7", new FinancialLineDTO("MALİYET HESAPLARI (7/A SEÇENEĞİ)")],
    ["70", new FinancialLineDTO("MALİYET MUHASEBESİ BAĞLANTI HESAPLARI", "7")],
    ["700", new FinancialLineDTO("MALİYET MUHASEBESİ BAĞLANTI HESABI", "70")],
    ["701", new FinancialLineDTO("MALİYET MUHASEBESİ YANSITMA HESABI", "70")],
    ["71", new FinancialLineDTO("DİREKT İLKMADDE VE MALZEME GİDERLERİ", "7")],
    ["710", new FinancialLineDTO("DİREKT İLKMADDE VE MALZEME GİDERLERİ", "71")],
    ["711", new FinancialLineDTO("DİREKT İLKMADDE VE MALZEME YANSITMA HESABI", "71")],
    ["712", new FinancialLineDTO("DİREKT İLKMADDE VE MALZEME FİYAT FARKI", "71")],
    ["713", new FinancialLineDTO("DİREKT İLKMADDE VE MALZEME MİKTAR FARKI", "71")],
    ["72", new FinancialLineDTO("DİREKT İŞÇİLİK GİDERLERİ", "7")],
    ["720", new FinancialLineDTO("DİREKT İŞÇİLİK GİDERLERİ", "72")],
    ["721", new FinancialLineDTO("DİREKT İŞCİLİK GİDERLERİ YANSITMA HESABI", "72")],
    ["722", new FinancialLineDTO("DİREKT İŞÇİLİK ÜCRET FARKLARI", "72")],
    ["723", new FinancialLineDTO("DİREKT İŞÇİLİK SÜRE (ZAMAN) FARKLARI", "72")],
    ["73", new FinancialLineDTO("GENEL ÜRETİM GİDERLERİ", "7")],
    ["730", new FinancialLineDTO("GENEL ÜRETİM GİDERLERİ", "73")],
    ["731", new FinancialLineDTO("GENEL ÜRETİM GİDERLERİ YANSITMA HESABI", "73")],
    ["732", new FinancialLineDTO("GENEL ÜRETİM GİDERLERİ BÜTÇE FARKLARI", "73")],
    ["733", new FinancialLineDTO("GENEL ÜRETİM GİDERLERİ VERİMLİLİK FARKLARI", "73")],
    ["734", new FinancialLineDTO("GENEL ÜRETİM GİDERLERİ KAPASİTE FARKLARI", "73")],
    ["74", new FinancialLineDTO("HİZMET ÜRETİM MALİYETİ", "7")],
    ["740", new FinancialLineDTO("HİZMET ÜRETİM MALİYETİ", "74")],
    ["741", new FinancialLineDTO("HİZMET ÜRETİM MALİYETİ YANSITMA HESABI", "74")],
    ["742", new FinancialLineDTO("HİZMET ÜRETİM MALİYETİ FARK HESAPLARI", "74")],
    ["75", new FinancialLineDTO("ARAŞTIRMA VE GELİŞTİRME GİDERLERİ", "7")],
    ["750", new FinancialLineDTO("ARAŞTIRMA VE GELİŞTİRME GİDERLERİ", "75")],
    ["751", new FinancialLineDTO("ARAŞTIRMA VE GELİŞTİRME GİDERLERİ YANSITMA HESABI", "75")],
    ["752", new FinancialLineDTO("ARAŞTIRMA VE GELİŞTİRME GİDER FARKLARI", "75")],
    ["76", new FinancialLineDTO("PAZARLAMA SATIŞ YE DAĞITIM GİDERLERİ", "7")],
    ["760", new FinancialLineDTO("PAZARLAMA SATIŞ VE DAĞITIM GİDERLERİ", "76")],
    ["761", new FinancialLineDTO("PAZARLAMA SATIŞ VE DAĞITIM GİDERLERİ YANSITMA HESABI", "76")],
    ["762", new FinancialLineDTO("PAZARLAMA SATIŞ VE DAĞITIM GİDERLERİ FARK HESABI", "76")],
    ["77", new FinancialLineDTO("GENEL YÖNETİM GİDERLERİ", "7")],
    ["770", new FinancialLineDTO("GENEL YÖNETİM GİDERLERİ", "77")],
    ["771", new FinancialLineDTO("GENEL YÖNETİM GİDERLERİ YANSITMA HESABI", "77")],
    ["772", new FinancialLineDTO("GENEL YÖNETİM GİDER FARKLARI HESABI", "77")],
    ["78", new FinancialLineDTO("FİNANSMAN GİDERLERİ", "7")],
    ["780", new FinancialLineDTO("FİNANSMAN GİDERLERİ", "78")],
    ["781", new FinancialLineDTO("FİNANSMAN GİDERLERİ YANSITMA HESABI", "78")],
    ["782", new FinancialLineDTO("FİNANSMAN GİDERLERİ FARK HESABI", "78")],
    ["79", new FinancialLineDTO("GİDER ÇEŞİTLERİ (7/B SEÇENEĞİ)", "7")],
    ["790", new FinancialLineDTO("İLKMADDE VE MALZEME GİDERLERİ", "79")],
    ["791", new FinancialLineDTO("İŞÇİ ÜCRET VE GİDERLERİ", "79")],
    ["792", new FinancialLineDTO("MEMUR ÜCRET VE GİDERLERİ", "79")],
    ["793", new FinancialLineDTO("DIŞARIDAN SAĞLANAN FAYDA VE HİZMETLER", "79")],
    ["794", new FinancialLineDTO("ÇEŞİTLİ GİDERLER", "79")],
    ["795", new FinancialLineDTO("VERGİ, RESİM VE HARÇLAR", "79")],
    ["796", new FinancialLineDTO("AMORTİSMANLAR VE TÜKENME PAYLARI", "79")],
    ["797", new FinancialLineDTO("FİNANSMAN GİDERLERİ", "79")],
    ["798", new FinancialLineDTO("GİDER ÇEŞİTLERİ YANSITMA HESABI", "79")],
    ["799", new FinancialLineDTO("ÜRETİM MALİYET HESABI", "79")],
    ["8", new FinancialLineDTO("(SERBEST)")],
    ["9", new FinancialLineDTO("NAZIM HESAPLAR")],
    ["0", new FinancialLineDTO("(SERBEST)")]
]);

export const FINANCIALS_DATABASE_ID = "654769c9344dffc7dd50";
export const FINANCIALS_COLLECTION_ID = "65476a3574077c3ce39a";

export const FinancialService = {
    async getFinancials() {
        let res = await fetch('/demo/data/financials.json', {headers: {'Cache-Control': 'no-cache'}});
        let d: any = await res.json();
        return d.data as Financial[];
    },

    async list(queries: string[] = []) {
        queries.push(Query.orderDesc("$createdAt"), Query.limit(10))
        return await databases.listDocuments(
            FINANCIALS_DATABASE_ID,
            FINANCIALS_COLLECTION_ID,
            queries
        );
    },

    async add(financial: Financial) {
        return await databases.createDocument(
            FINANCIALS_DATABASE_ID,
            FINANCIALS_COLLECTION_ID,
            ID.unique(),
            financial
        );
    },

    async update(id: string, data: Financial) {
        return await databases.updateDocument(FINANCIALS_DATABASE_ID, FINANCIALS_COLLECTION_ID, id, {...data})
    },

    async remove(id: string) {
        return await databases.deleteDocument(FINANCIALS_DATABASE_ID, FINANCIALS_COLLECTION_ID, id);
    },

    async removeAll(ids: string[]) {
        for (const id of ids) {
            await this.remove(id)
        }
    },

    calculateSum(node: TreeNode, field: any): number {
        if (node.children == undefined || node.children.length === 0) {
            if (node.data.type === FinancialLineType.PLUS) {
                return node.data[field]
            } else {
                return -node.data[field]
            }
        }
        let sum = 0;
        node.children.forEach(child => {
            if (node.data.type === FinancialLineType.PLUS) {
                sum += this.calculateSum(child, field);
            } else {
                sum -= this.calculateSum(child, field);
            }
        });
        node.data[field] = sum;
        return sum;
    },

    createLines(lines: { [key: string]: {value:number, id:string}  }, revisedLines: { [key: string]: {value:number, id:string}  }) {
        let datas: TreeNode[] = []
        let map = new Map<string, TreeNode>()
        DefaultAccountCode.forEach((account, key: string) => {
            account.key = key
            if (lines[key] != null) {
                account.value = Number(lines[key].value)
                account.revised = account.value
                account.$id = lines[key].id
            } else {
                account.value = 0
                account.revised = 0
            }
            if (revisedLines[key] != null) {
                account.revised = Number(revisedLines[key].value)
                account.$id = revisedLines[key].id
            }
            if (account.parentKey == null) {
                let node: TreeNode = {key: key, label: account.name, data: account, children: []}
                map.set(key, node)
                datas.push(node)
            } else {
                let node: TreeNode = {key: key, label: account.name, data: account, children: []}
                map.get(account.parentKey)?.children?.push(node)
                map.set(key, node)
            }
        });
        datas.forEach((line) => {
            this.calculateSum(line, 'value')
            this.calculateSum(line, 'revised')
        })

        return [datas, map]
    }
}


