export const SpecialLines:{[key: string]: any} = {
    "GROSS_PROFIT": {name: "Brüt Satış Karı veya Zararı", accountCode: "GROSS_PROFIT"},
    "OPERATING_PROFIT": {name: "Faaliyet Karı veya Zararı", accountCode: "OPERATING_PROFIT"},
    "ORDINARY_PROFIT": {name: "Olağan Kar veya Zarar", accountCode: "ORDINARY_PROFIT"},
    "PERIOD_PROFIT": {name: "Dönem Karı veya Zararı", accountCode: "690"},
    "PERIOD_NET_PROFIT": {name: "Dönem Net Karı veya Zararı", accountCode: "692"},
}

export const BeyannameCodes:{[key: string]: any} = {
    "I.": {name: "DÖNEN VARLIKLAR", accountCode: "1"},
    "I.A.": {name: "HAZIR DEĞERLER", accountCode: "10"},
    "I.A.1.": {name: "KASA", accountCode: "100"},
    "I.A.2.": {name: "ALINAN ÇEKLER", accountCode: "101"},
    "I.A.3.": {name: "BANKALAR", accountCode: "102"},
    "I.A.4.": {name: "VERİLEN ÇEKLER VE ÖDEME EMİRLERİ (-)", accountCode: "103"},
    "I.A.5.": {name: "DİĞER HAZIR DEĞERLER", accountCode: "108"},
    "I.B.": {name: "MENKUL KIYMETLER", accountCode: "11"},
    "I.B.1.": {name: "HİSSE SENETLERİ", accountCode: "110"},
    "I.B.2.": {name: "ÖZEL KESİM TAHVİL, SENET VE BONOLARI", accountCode: "111"},
    "I.B.3.": {name: "KAMU KESİMİ TAHVİL, SENET VE BONOLARI", accountCode: "112"},
    "I.B.4.": {name: "DİĞER MENKUL KIYMETLER", accountCode: "118"},
    "I.B.10.": {name: "MENKUL KIYMETLER DEĞER DÜŞÜKLÜĞÜ KARŞILIĞI (-)", accountCode: "119"},
    "I.C.": {name: "TİCARİ ALACAKLAR", accountCode: "12"},
    "I.C.1.": {name: "ALICILAR", accountCode: "120"},
    "I.C.2.": {name: "ALACAK SENETLERİ", accountCode: "121"},
    "I.C.3.": {name: "ALACAK SENETLERİ REESKONTU (-)", accountCode: "122"},
    "I.C.4.": {name: "KAZANILMAMIŞ FİNANSAL KİRALAMA FAİZ GELİRLERİ (-)", accountCode: "124"},
    "I.C.5.": {name: "VERİLEN DEPOZİTO VE TEMİNATLAR", accountCode: "126"},
    "I.C.6.": {name: "DİĞER TİCARİ ALACAKLAR SENET VE BONOLARI", accountCode: "127"},
    "I.C.7.": {name: "ŞÜPHELİ TİCARİ ALACAKLAR", accountCode: "128"},
    "I.C.8.": {name: "ŞÜPHELİ TİCARİ ALACAKLAR KARŞILIĞI (-)", accountCode: "129"},
    "I.D.": {name: "DİĞER ALACAKLAR", accountCode: "13"},
    "I.D.1.": {name: "ORTAKLARDAN ALACAKLAR", accountCode: "131"},
    "I.D.2.": {name: "İŞTİRAKLERDEN ALACAKLAR", accountCode: "132"},
    "I.D.3.": {name: "BAĞLI ORTAKLIKLARDAN ALACAKLAR", accountCode: "133"},
    "I.D.5.": {name: "PERSONELDEN ALACAKLAR", accountCode: "135"},
    "I.D.6.": {name: "DİĞER ÇEŞİTLİ ALACAKLAR", accountCode: "136"},
    "I.D.7.": {name: "DİĞER ALACAK SENETLERİ REESKONTU (-)", accountCode: "137"},
    "I.D.8.": {name: "ŞÜPHELİ DİĞER ALACAKLAR", accountCode: "138"},
    "I.D.9.": {name: "ŞÜPHELİ DİĞER ALACAKLAR KARŞILIĞI (-)", accountCode: "139"},
    "I.E.": {name: "STOKLAR", accountCode: "15"},
    "I.E.1.": {name: "İLK MADDE VE MALZEME", accountCode: "150"},
    "I.E.2.": {name: "YARI MAMULLER - ÜRETİM", accountCode: "151"},
    "I.E.3.": {name: "MAMÜLLER", accountCode: "152"},
    "I.E.4.": {name: "TİCARİ MALLAR", accountCode: "153"},
    "I.E.5.": {name: "DİĞER STOKLAR", accountCode: "157"},
    "I.E.6.": {name: "STOK DEĞER DÜŞÜKLÜĞÜ KARŞILIĞI (-)", accountCode: "158"},
    "I.E.7.": {name: "VERİLEN SİPARİŞ AVANSLARI", accountCode: "159"},
    "I.G.": {name: "GELECEK AYLARA AİT GİDERLER VE GELİR TAHAKKUKLARI", accountCode: "18"},
    "I.G.1.": {name: "GELECEK AYLARA AİT GİDERLER", accountCode: "180"},
    "I.G.2.": {name: "GELİR TAHAKKUKLARI", accountCode: "181"},
    "I.H.": {name: "DİĞER DÖNEN VARLIKLAR", accountCode: "19"},
    "I.H.1.": {name: "İNDİRİLECEK KATMA DEĞER VERGİSİ", accountCode: "191"},
    "I.H.2.": {name: "DİĞER KATMA DEĞER VERGİSİ", accountCode: "192"},
    "I.H.3.": {name: "PEŞİN ÖDENEN VERGİLER VE FONLAR", accountCode: "193"},
    "I.H.4.": {name: "PERSONEL AVANSLARI", accountCode: "196"},
    "I.H.5.": {name: "SAYIM VE TESELLÜM NOKSANLARI", accountCode: "197"},
    "I.H.6.": {name: "DİĞER ÇEŞİTLİ DÖNEN VARLIKLAR", accountCode: "198"},
    "I.H.7.": {name: "DİĞER DÖNEN VARLIKLAR KARŞILIĞI (-)", accountCode: "199"},
    "II.": {name: "DURAN VARLIKLAR", accountCode: "2"},
    "II.A.": {name: "TİCARİ ALACAKLAR", accountCode: "22"},
    "II.A.1.": {name: "ALICILAR", accountCode: "220"},
    "II.A.2.": {name: "ALACAK SENETLERİ", accountCode: "221"},
    "II.A.3.": {name: "ALACAK SENETLERİ REESKONTU (-)", accountCode: "222"},
    "II.A.4.": {name: "VERİLEN DEPOZİTO VE TEMİNATLAR", accountCode: "226"},
    "II.A.5.": {name: "ŞÜPHELİ ALACAKLAR KARŞILIĞI (-)", accountCode: "229"},
    "II.B.": {name: "DİĞER ALACAKLAR", accountCode: "23"},
    "II.B.1.": {name: "ORTAKLARDAN ALACAKLAR", accountCode: "230"},
    "II.B.2.": {name: "İŞTİRAKLERDEN ALACAKLAR", accountCode: "231"},
    "II.B.3.": {name: "BAĞLI ORTAKLIKLARDAN ALACAKLAR", accountCode: "232"},
    "II.B.4.": {name: "PERSONELDEN ALACAKLAR", accountCode: "235"},
    "II.B.5.": {name: "DİĞER ÇEŞİTLİ ALACAKLAR", accountCode: "236"},
    "II.B.6.": {name: "DİĞER ALACAK SENETLERİ REESKONTU (-)", accountCode: "237"},
    "II.B.7.": {name: "ŞÜPHELİ DİĞER ALACAKLAR KARŞILIĞI (-)", accountCode: "239"},
    "II.C.": {name: "MALİ DURAN VARLIKLAR", accountCode: "24"},
    "II.C.1.": {name: "BAĞLI MENKUL KIYMETLER", accountCode: "240"},
    "II.C.2.": {name: "BAĞLI MENKUL KIYMETLER DEĞER DÜŞÜKLÜĞÜ KARŞILIĞI (-)", accountCode: "241"},
    "II.C.3.": {name: "İŞTİRAKLER", accountCode: "242"},
    "II.C.4.": {name: "İŞTİRAKLERE SERMAYE TAAHHÜTLERİ (-)", accountCode: "243"},
    "II.C.5.": {name: "İŞTİRAKLER SERMAYE PAYLARI DEĞER DÜŞÜKLÜĞÜ KARŞILIĞI (-)", accountCode: "244"},
    "II.C.6.": {name: "BAĞLI ORTAKLIKLAR", accountCode: "245"},
    "II.C.7.": {name: "BAĞLI ORTAKLIKLARA SERMAYE TAAHHÜTLERİ (-)", accountCode: "246"},
    "II.C.8.": {name: "BAĞLI ORTAKLIKLAR SERMAYE PAYLARI DEĞER DÜŞÜKLÜGÜ KARŞILIĞI (-)", accountCode: "247"},
    "II.C.9.": {name: "DİĞER MALİ DURAN VARLIKLAR", accountCode: "248"},
    "II.C.10.": {name: "DİĞER MALİ DURAN VARLIKLAR KARŞILIĞI (-)", accountCode: "249"},
    "II.D.": {name: "MADDİ DURAN VARLIKLAR", accountCode: "25"},
    "II.D.1.": {name: "ARAZİ VE ARSALAR", accountCode: "250"},
    "II.D.2.": {name: "YER ALTI VE YER ÜSTÜ DÜZENLERİ", accountCode: "251"},
    "II.D.3.": {name: "BİNALAR", accountCode: "252"},
    "II.D.4.": {name: "TESİS, MAKİNE VE CİHAZLAR", accountCode: "253"},
    "II.D.5.": {name: "TAŞITLAR", accountCode: "254"},
    "II.D.6.": {name: "DEMİRBAŞLAR", accountCode: "255"},
    "II.D.7.": {name: "DİĞER MADDİ DURAN VARLIKLAR", accountCode: "256"},
    "II.D.8.": {name: "BİRİKMİŞ AMORTİSMANLAR (-)", accountCode: "257"},
    "II.D.9.": {name: "YAPILMAKTA OLAN YATIRIMLAR", accountCode: "258"},
    "II.D.10.": {name: "VERİLEN AVANSLAR", accountCode: "259"},
    "II.E.": {name: "MADDİ OLMAYAN DURAN VARLIKLAR", accountCode: "26"},
    "II.E.1.": {name: "HAKLAR", accountCode: "260"},
    "II.E.2.": {name: "ŞEREFİYE", accountCode: "261"},
    "II.E.3.": {name: "KURULUŞ VE ÖRGÜTLENME GİDERLERİ", accountCode: "262"},
    "II.E.4.": {name: "ARAŞTIRMA VE GELİŞTİRME GİDERLERİ", accountCode: "263"},
    "II.E.5.": {name: "ÖZEL MALİYETLER", accountCode: "264"},
    "II.E.6.": {name: "DİĞER MADDİ OLMAYAN DURAN VARLIKLAR", accountCode: "267"},
    "II.E.7.": {name: "BİRİKMİŞ AMORTİSMANLAR (-)", accountCode: "268"},
    "II.E.8.": {name: "VERİLEN AVANSLAR", accountCode: "269"},
    "II.F.": {name: "ÖZEL TÜKENMEYE TABİ VARLIKLAR", accountCode: "27"},
    "II.F.1.": {name: "ARAMA GİDERLERİ", accountCode: "271"},
    "II.F.2.": {name: "HAZIRLIK VE GELİŞTİRME GİDERLERİ", accountCode: "272"},
    "II.F.3.": {name: "DİĞER ÖZEL TÜKENMEYE TABİ VARLIKLAR", accountCode: "277"},
    "II.F.4.": {name: "BİRİKMİŞ TÜKENME PAYLARI (-)", accountCode: "278"},
    "II.F.9.": {name: "VERİLEN AVANSLAR", accountCode: "279"},
    "II.G.": {name: "GELECEK YILLARA AİT GİDERLER VE GELİR TAHAKKUKLARI", accountCode: "28"},
    "II.G.1.": {name: "GELECEK YILLARA AİT GİDERLER", accountCode: "280"},
    "II.G.2.": {name: "GELİR TAHAKKUKLARI", accountCode: "281"},
    "II.H.": {name: "DİĞER DURAN VARLIKLAR", accountCode: "29"},
    "II.H.1.": {name: "GELECEK YILLARDA İNDİRİLECEK KATMA DEĞER VERGİSİ", accountCode: "291"},
    "II.H.2.": {name: "DİĞER KATMA DEĞER VERGİSİ", accountCode: "292"},
    "II.H.3.": {name: "GELECEK YILLAR İHTİYACI STOKLAR", accountCode: "293"},
    "II.H.4.": {name: "ELDEN ÇIKARILACAK STOKLAR VE MADDİ DURAN VARLIKLAR", accountCode: "294"},
    "II.H.5.": {name: "DİĞER ÇEŞİTLİ DURAN VARLIKLAR", accountCode: "297"},
    "II.H.6.": {name: "STOK DEĞER DÜŞÜKLÜĞÜ KARŞILIĞI (-)", accountCode: "298"},
    "II.H.7.": {name: "BİRİKMİŞ AMORTİSMANLAR (-)", accountCode: "299"},
    "III.": {name: "KISA VADELİ YABANCI KAYNAKLAR", accountCode: "3"},
    "III.A.": {name: "MALİ BORÇLAR", accountCode: "30"},
    "III.A.1.": {name: "BANKA KREDİLERİ", accountCode: "300"},
    "III.A.2.": {name: "UZUN VADELİ KREDİLERİN ANAPARA TAKSİTLERİ VE FAİZLERİ", accountCode: "303"},
    "III.A.3.": {name: "TAHVİL ANAPARA BORÇ, TAKSİT VE FAİZLERİ", accountCode: "304"},
    "III.A.4.": {name: "ÇIKARILMIŞ BONOLAR VE SENETLER", accountCode: "305"},
    "III.A.5.": {name: "ÇIKARILMIŞ DİĞER MENKUL KIYMETLER", accountCode: "306"},
    "III.A.6.": {name: "MENKUL KIYMETLER İHRAÇ FARKI (-)", accountCode: "308"},
    "III.A.7.": {name: "DİĞER MALİ BORÇLAR", accountCode: "309"},
    "III.B.": {name: "TİCARİ BORÇLAR", accountCode: "32"},
    "III.B.1.": {name: "SATICILAR", accountCode: "320"},
    "III.B.2.": {name: "BORÇ SENETLERİ", accountCode: "321"},
    "III.B.3.": {name: "BORÇ SENETLERİ REESKONTU (-)", accountCode: "322"},
    "III.B.4.": {name: "ALINAN DEPOZİTO VE TEMİNATLAR", accountCode: "326"},
    "III.B.5.": {name: "DİĞER TİCARİ BORÇLAR", accountCode: "329"},
    "III.C.": {name: "DİĞER BORÇLAR", accountCode: "33"},
    "III.C.1.": {name: "ORTAKLARA BORÇLAR", accountCode: "331"},
    "III.C.2.": {name: "İŞTİRAKLERE BORÇLAR", accountCode: "332"},
    "III.C.3.": {name: "BAĞLI ORTAKLIKLARA BORÇLAR", accountCode: "333"},
    "III.C.4.": {name: "PERSONELE BORÇLAR", accountCode: "335"},
    "III.C.5.": {name: "DİĞER BORÇ SENETLERİ REESKONTU (-)", accountCode: "337"},
    "III.C.6.": {name: "DİĞER ÇEŞİTLİ BORÇLAR(1)", accountCode: "339"},
    "III.D.": {name: "ALINAN AVANSLAR", accountCode: "34"},
    "III.D.1.": {name: "ALINAN SİPARİŞ AVANSLARI", accountCode: "340"},
    "III.D.2.": {name: "ALINAN DİĞER AVANSLAR", accountCode: "349"},
    "III.F.": {name: "ÖDENECEK VERGİ VE DİĞER YÜKÜMLÜLÜKLER", accountCode: "36"},
    "III.F.1.": {name: "ÖDENECEK VERGİ VE FONLAR", accountCode: "360"},
    "III.F.2.": {name: "ÖDENECEK SOSYAL GÜVENLİK KESİNTİLERİ", accountCode: "361"},
    "III.F.3.": {name: "VADESİ GEÇMİŞ ERTELENMİŞ VEYA TAKSİTLENDİRİLMİŞ VERGİ VE DİĞER YÜKÜMLÜLÜKLER", accountCode: "368"},
    "III.F.4.": {name: "ÖDENECEK DİĞER YÜKÜMLÜLÜKLER", accountCode: "369"},
    "III.G.": {name: "BORÇ VE GİDER KARŞILIKLARI", accountCode: "37"},
    "III.G.1.": {name: "DÖNEM KARI VERGİ VE DİĞER YASAL YÜKÜMLÜLÜK KARŞILIKLARI", accountCode: "370"},
    "III.G.2.": {name: "DÖNEM KARININ PEŞİN ÖDENEN VERGİ VE DİĞER YÜKÜMLÜLÜKLERİ (-)", accountCode: "371"},
    "III.G.3.": {name: "KIDEM TAZMİNATI KARŞILIĞI", accountCode: "372"},
    "III.G.4.": {name: "MALİYET GİDERLERİ KARŞILIĞI", accountCode: "373"},
    "III.G.5.": {name: "DİĞER BORÇ VE GİDER KARŞILIKLARI", accountCode: "379"},
    "III.H.": {name: "GELECEK AYLARA AİT GELİRLER VE GİDER TAHAKKUKLARI", accountCode: "38"},
    "III.H.1.": {name: "GELECEK AYLARA AİT GELİRLER", accountCode: "380"},
    "III.H.2.": {name: "GİDER TAHAKKUKLARI", accountCode: "381"},
    "III.I.": {name: "DİĞER KISA VADELİ YABANCI KAYNAKLAR", accountCode: "39"},
    "III.I.1.": {name: "HESAPLANAN KDV", accountCode: "391"},
    "III.I.2.": {name: "DİĞER KDV", accountCode: "392"},
    "III.I.3.": {name: "SAYIM VE TESELLÜM FAZLALARI(1)", accountCode: "398"},
    "III.I.4.": {name: "DİĞER ÇEŞİTLİ YABANCI KAYNAKLAR", accountCode: "399"},
    "IV.": {name: "UZUN VADELİ YABANCI KAYNAKLAR", accountCode: "4"},
    "IV.A.": {name: "MALİ BORÇLAR", accountCode: "40"},
    "IV.A.1.": {name: "BANKA KREDİLERİ", accountCode: "400"},
    "IV.A.2.": {name: "ÇIKARILMIŞ TAHVİLLER", accountCode: "405"},
    "IV.A.3.": {name: "ÇIKARILMIŞ DİĞER MENKUL KIYMETLER", accountCode: "407"},
    "IV.A.4.": {name: "MENKUL KIYMETLER İHRAÇ FARKI (-)", accountCode: "408"},
    "IV.A.5.": {name: "DİĞER MALİ BORÇLAR", accountCode: "409"},
    "IV.B.": {name: "TİCARİ BORÇLAR", accountCode: "42"},
    "IV.B.0.": {name: "SATICILAR", accountCode: "420"},
    "IV.B.1.": {name: "BORÇ SENETLERİ", accountCode: "421"},
    "IV.B.2.": {name: "BORÇ SENETLERİ REESKONTU (-)", accountCode: "422"},
    "IV.B.6.": {name: "ALINAN DEPOZİTO VE TEMİNATLAR", accountCode: "426"},
    "IV.B.9.": {name: "DİĞER TİCARİ BORÇLAR", accountCode: "429"},
    "IV.C.": {name: "DİĞER BORÇLAR", accountCode: "43"},
    "IV.C.1.": {name: "ORTAKLARA BORÇLAR", accountCode: "431"},
    "IV.C.2.": {name: "İŞTİRAKLERE BORÇLAR", accountCode: "432"},
    "IV.C.3.": {name: "BAĞLI ORTAKLIKLARA BORÇLAR", accountCode: "433"},
    "IV.C.7.": {name: "DİĞER BORÇ SENETLERİ REESKONTU (-)", accountCode: "437"},
    "IV.C.8.": {name: "KAMUYA OLAN ERTELENMİŞ VEYA TAKSİTLENDİRİLMİŞ BORÇLAR", accountCode: "438"},
    "IV.C.9.": {name: "DİĞER ÇEŞİTLİ BORÇLAR(1)", accountCode: "439"},
    "IV.D.": {name: "ALINAN AVANSLAR", accountCode: "44"},
    "IV.D.0.": {name: "ALINAN SİPARİŞ AVANSLARI", accountCode: "440"},
    "IV.D.9.": {name: "ALINAN DİĞER AVANSLAR", accountCode: "449"},
    "IV.E.": {name: "BORÇ VE GİDER KARŞILIKLARI", accountCode: "47"},
    "IV.E.2.": {name: "KIDEM TAZMİNATI KARŞILIĞI", accountCode: "472"},
    "IV.E.9.": {name: "DİĞER BORÇ VE GİDER KARŞILIKLARI", accountCode: "479"},
    "IV.F.": {name: "GELECEK YILLARA AİT GELİRLER VE GİDER TAHAKKUKLARI", accountCode: "48"},
    "IV.F.0.": {name: "GELECEK YILLARA AİT GELİRLER", accountCode: "480"},
    "IV.F.1.": {name: "GİDER TAHAKKUKLARI", accountCode: "481"},
    "IV.G.": {name: "DİĞER UZUN VADELİ YABANCI KAYNAKLAR", accountCode: "49"},
    "IV.G.2.": {name: "GELECEK YILLARA ERTELENEN VEYA TERKİN EDİLEN KATMA DEĞER VERGİSİ(1)", accountCode: "492"},
    "IV.G.3.": {name: "TESİSE KATILMA PAYLARI", accountCode: "493"},
    "IV.G.9.": {name: "DİĞER ÇEŞİTLİ UZUN VADELİ YABANCI KAYNAKLAR", accountCode: "499"},
    "V.": {name: "ÖZ KAYNAKLAR", accountCode: "5"},
    "V.A.": {name: "ÖDENMİŞ SERMAYE", accountCode: "50"},
    "V.A.1.": {name: "SERMAYE", accountCode: "500"},
    "V.A.2.": {name: "ÖDENMEMİŞ SERMAYE (-)", accountCode: "501"},
    "V.B.": {name: "SERMAYE YEDEKLERİ", accountCode: "52"},
    "V.B.1.": {name: "HİSSE SENETLERİ İHRAÇ PRİMLERİ", accountCode: "520"},
    "V.B.2.": {name: "HİSSE SENEDİ İPTAL KARLARI", accountCode: "521"},
    "V.B.3.": {name: "M.D.V. YENİDEN DEĞERLEME ARTIŞLARI", accountCode: "522"},
    "V.B.4.": {name: "İŞTİRAKLER YENİDEN DEĞERLEME ARTIŞLARI", accountCode: "523"},
    "V.B.5.": {name: "DİĞER SERMAYE YEDEKLERİ", accountCode: "529"},
    "V.C.": {name: "KAR YEDEKLERİ", accountCode: "54"},
    "V.C.1.": {name: "YASAL YEDEKLER", accountCode: "540"},
    "V.C.2.": {name: "STATÜ YEDEKLERİ", accountCode: "541"},
    "V.C.3.": {name: "OLAĞANÜSTÜ YEDEKLER", accountCode: "542"},
    "V.C.4.": {name: "DİĞER KAR YEDEKLERİ", accountCode: "548"},
    "V.C.5.": {name: "ÖZEL FONLAR", accountCode: "549"},
    "V.D.": {name: "GEÇMİŞ YILLAR KARLARI", accountCode: "57"},
    "V.D.1.": {name: "GEÇMİŞ YILLAR KARLARI", accountCode: "570"},
    "V.E.": {name: "GEÇMİŞ YILLAR ZARARLARI (-)", accountCode: "58"},
    "V.E.1.": {name: "GEÇMİŞ YILLAR ZARARLARI", accountCode: "580"},
    "V.F.": {name: "DÖNEM NET KARI (ZARARI)", accountCode: "59"},
    "V.F.1.": {name: "DÖNEM NET KARI", accountCode: "590"},
    "V.F.2.": {name: "DÖNEM NET ZARARI (-)", accountCode: "591"},
    "VI.": {name: "GELİR TABLOSU HESAPLARI", accountCode: "6"},
    "VI.A.": {name: "BRÜT SATIŞLAR", accountCode: "60"},
    "VI.A.1.": {name: "YURTİÇİ SATIŞLAR", accountCode: "600"},
    "VI.A.2.": {name: "YURTDIŞI SATIŞLAR", accountCode: "601"},
    "VI.A.3.": {name: "DİĞER GELİRLER", accountCode: "602"},
    "VI.B.": {name: "SATIŞ İNDİRİMLERİ (-)", accountCode: "61"},
    "VI.B.1.": {name: "SATIŞTAN İADELER (-)", accountCode: "610"},
    "VI.B.2.": {name: "SATIŞ İSKONTOLARI (-)", accountCode: "611"},
    "VI.B.3.": {name: "DİĞER İNDİRİMLER (-)", accountCode: "612"},
    "VI.C.": {name: "NET SATIŞLAR", accountCode: "NET_SALES"},
    "VI.D.": {name: "SATIŞLARIN MALİYETİ (-)", accountCode: "62"},
    "VI.D.1.": {name: "SATILAN MAMÜLLER MALİYETİ (-)", accountCode: "620"},
    "VI.D.2.": {name: "SATILAN TİCARİ MALLAR MALİYETİ (-)", accountCode: "621"},
    "VI.D.3.": {name: "SATILAN HİZMET MALİYETİ (-)", accountCode: "622"},
    "VI.D.4.": {name: "DİĞER SATIŞLARIN MALİYETİ (-)", accountCode: "623"},
    "VI.E.": {name: "FAALİYET GİDERLERİ (-)", accountCode: "63"},
    "VI.E.1.": {name: "ARAŞTIRMA VE GELİŞTİRME GİDERLERİ (-)", accountCode: "630"},
    "VI.E.2.": {name: "PAZARLAMA SATIŞ VE DAĞITIM GİDERLERİ", accountCode: "631"},
    "VI.E.3.": {name: "GENEL YÖNETİM GİDERLERİ (-)", accountCode: "632"},
    "VI.F.": {name: "DİĞER FAALİYETLERDEN OLAĞAN GELİR VE KARLAR", accountCode: "64"},
    "VI.F.1.": {name: "İŞTİRAKLERDEN TEMETTÜ GELİRLERİ", accountCode: "640"},
    "VI.F.2.": {name: "BAĞLI ORTAKLIKLARDAN TEMETTÜ GELİRLERİ", accountCode: "641"},
    "VI.F.3.": {name: "FAİZ GELİRLERİ", accountCode: "642"},
    "VI.F.4.": {name: "KOMİSYON GELİRLERİ", accountCode: "643"},
    "VI.F.5.": {name: "KONUSU KALMAYAN KARŞILIKLAR", accountCode: "644"},
    "VI.F.6.": {name: "MENKUL KIYMET SATIŞ KARLARI", accountCode: "645"},
    "VI.F.7.": {name: "KAMBİYO KARLARI", accountCode: "646"},
    "VI.F.8.": {name: "REESKONT FAİZ GELİRLERİ", accountCode: "647"},
    "VI.F.9.": {name: "ENFLASYON DÜZELTMESİ KARLARI", accountCode: "648"},
    "VI.F.10.": {name: "FAALİYETLE İLGİLİ DİĞER GELİR VE KARLAR", accountCode: "649"},
    "VI.G.": {name: "DİĞER FAALİYETLERDEN OLAĞAN GİDER VE ZARARLAR (-)", accountCode: "65"},
    "VI.G.1.": {name: "KOMİSYON GİDERLERİ (-)", accountCode: "653"},
    "VI.G.2.": {name: "KARŞILIK GİDERLERİ (-)", accountCode: "654"},
    "VI.G.3.": {name: "MENKUL KIYMET SATIŞ ZARARLARI (-)", accountCode: "655"},
    "VI.G.4.": {name: "KAMBİYO ZARARLARI (-)", accountCode: "656"},
    "VI.G.5.": {name: "REESKONT FAİZ GİDERLERİ (-)", accountCode: "657"},
    "VI.G.6.": {name: "ENFLASYON DÜZELTMESİ ZARARLARI (-)", accountCode: "658"},
    "VI.G.7.": {name: "DİĞER OLAĞAN GİDER VE ZARARLAR (-)", accountCode: "659"},
    "VI.H.": {name: "FİNANSMAN GİDERLERİ (-)", accountCode: "66"},
    "VI.H.1.": {name: "KISA VADELİ BORÇLANMA GİDERLERİ (-)", accountCode: "660"},
    "VI.H.2.": {name: "UZUN VADELİ BORÇLANMA GİDERLERİ (-)", accountCode: "661"},
    "VI.I.": {name: "OLAĞANDIŞI GELİR VE KARLAR", accountCode: "67"},
    "VI.I.1.": {name: "ÖNCEKİ DÖNEM GELİR VE KARLARI", accountCode: "671"},
    "VI.I.2.": {name: "DİĞER OLAĞANDIŞI GELİR VE KARLAR", accountCode: "679"},
    "VI.J.": {name: "OLAĞANDIŞI GİDER VE ZARARLAR (-)", accountCode: "68"},
    "VI.J.1.": {name: "ÇALIŞMAYAN KISIM GİDER VE ZARARLARI (-)", accountCode: "680"},
    "VI.J.2.": {name: "ÖNCEKİ DÖNEM GİDER VE ZARARLARI (-)", accountCode: "681"},
    "VI.J.3.": {name: "DİĞER OLAĞANDIŞI GİDER VE ZARARLAR (-)", accountCode: "689"},
    "VI.K.": {name: "DÖNEM NET KARI (ZARARI)", accountCode: "69"},
    "VI.K.1.": {name: "DÖNEM KARI VEYA ZARARI", accountCode: "690"},
    "VI.K.2.": {name: "DÖNEM KARI VERGİ VE DİĞER YASAL YÜKÜMLÜLÜK KARŞILIKLARI (-)", accountCode: "691"},
    "VI.K.3.": {name: "DÖNEM NET KARI VEYA ZARARI", accountCode: "692"},
    "VI.K.4.": {name: "YILLARA YAYGIN İNŞAAT ENFLASYON DÜZELTME", accountCode: "697"},
    "VI.K.5.": {name: "ENFLASYON DÜZELTME", accountCode: "698"},
    "VII.": {name: "MALİYET HESAPLARI (7/A SEÇENEĞİ)", accountCode: "7"},
    "VII.A.": {name: "MALİYET MUHASEBESİ BAĞLANTI HESAPLARI", accountCode: "70"},
    "VII.A.1.": {name: "MALİYET MUHASEBESİ BAĞLANTI HESABI", accountCode: "700"},
    "VII.A.2.": {name: "MALİYET MUHASEBESİ YANSITMA HESABI", accountCode: "701"},
    "VII.B.": {name: "DİREKT İLKMADDE VE MALZEME GİDERLERİ", accountCode: "71"},
    "VII.B.1.": {name: "DİREKT İLKMADDE VE MALZEME GİDERLERİ", accountCode: "710"},
    "VII.B.2.": {name: "DİREKT İLKMADDE VE MALZEME YANSITMA HESABI", accountCode: "711"},
    "VII.B.3.": {name: "DİREKT İLKMADDE VE MALZEME FİYAT FARKI", accountCode: "712"},
    "VII.B.4.": {name: "DİREKT İLKMADDE VE MALZEME MİKTAR FARKI", accountCode: "713"},
    "VII.C.": {name: "DİREKT İŞÇİLİK GİDERLERİ", accountCode: "72"},
    "VII.C.1.": {name: "DİREKT İŞÇİLİK GİDERLERİ", accountCode: "720"},
    "VII.C.2.": {name: "DİREKT İŞCİLİK GİDERLERİ YANSITMA HESABI", accountCode: "721"},
    "VII.C.3.": {name: "DİREKT İŞÇİLİK ÜCRET FARKLARI", accountCode: "722"},
    "VII.C.4.": {name: "DİREKT İŞÇİLİK SÜRE (ZAMAN) FARKLARI", accountCode: "723"},
    "VII.D.": {name: "GENEL ÜRETİM GİDERLERİ", accountCode: "73"},
    "VII.D.1.": {name: "GENEL ÜRETİM GİDERLERİ", accountCode: "730"},
    "VII.D.2.": {name: "GENEL ÜRETİM GİDERLERİ YANSITMA HESABI", accountCode: "731"},
    "VII.D.3.": {name: "GENEL ÜRETİM GİDERLERİ BÜTÇE FARKLARI", accountCode: "732"},
    "VII.D.4.": {name: "GENEL ÜRETİM GİDERLERİ VERİMLİLİK FARKLARI", accountCode: "733"},
    "VII.D.5.": {name: "GENEL ÜRETİM GİDERLERİ KAPASİTE FARKLARI", accountCode: "734"},
    "VII.E.": {name: "HİZMET ÜRETİM MALİYETİ", accountCode: "74"},
    "VII.E.1.": {name: "HİZMET ÜRETİM MALİYETİ", accountCode: "740"},
    "VII.E.2.": {name: "HİZMET ÜRETİM MALİYETİ YANSITMA HESABI", accountCode: "741"},
    "VII.E.3.": {name: "HİZMET ÜRETİM MALİYETİ FARK HESAPLARI", accountCode: "742"},
    "VII.F.": {name: "ARAŞTIRMA VE GELİŞTİRME GİDERLERİ", accountCode: "75"},
    "VII.F.1.": {name: "ARAŞTIRMA VE GELİŞTİRME GİDERLERİ", accountCode: "750"},
    "VII.F.2.": {name: "ARAŞTIRMA VE GELİŞTİRME GİDERLERİ YANSITMA HESABI", accountCode: "751"},
    "VII.F.3.": {name: "ARAŞTIRMA VE GELİŞTİRME GİDER FARKLARI", accountCode: "752"},
    "VII.G.": {name: "PAZARLAMA SATIŞ YE DAĞITIM GİDERLERİ", accountCode: "76"},
    "VII.G.1.": {name: "PAZARLAMA SATIŞ VE DAĞITIM GİDERLERİ", accountCode: "760"},
    "VII.G.2.": {name: "PAZARLAMA SATIŞ VE DAĞITIM GİDERLERİ YANSITMA HESABI", accountCode: "761"},
    "VII.G.3.": {name: "PAZARLAMA SATIŞ VE DAĞITIM GİDERLERİ FARK HESABI", accountCode: "762"},
    "VII.H.": {name: "GENEL YÖNETİM GİDERLERİ", accountCode: "77"},
    "VII.H.1.": {name: "GENEL YÖNETİM GİDERLERİ", accountCode: "770"},
    "VII.H.2.": {name: "GENEL YÖNETİM GİDERLERİ YANSITMA HESABI", accountCode: "771"},
    "VII.H.3.": {name: "GENEL YÖNETİM GİDER FARKLARI HESABI", accountCode: "772"},
    "VII.I.": {name: "FİNANSMAN GİDERLERİ", accountCode: "78"},
    "VII.I.1.": {name: "FİNANSMAN GİDERLERİ", accountCode: "780"},
    "VII.I.2.": {name: "FİNANSMAN GİDERLERİ YANSITMA HESABI", accountCode: "781"},
    "VII.I.3.": {name: "FİNANSMAN GİDERLERİ FARK HESABI", accountCode: "782"},
    "VII.J.": {name: "GİDER ÇEŞİTLERİ (7/B SEÇENEĞİ)", accountCode: "79"},
    "VII.J.1.": {name: "İLKMADDE VE MALZEME GİDERLERİ", accountCode: "790"},
    "VII.J.2.": {name: "İŞÇİ ÜCRET VE GİDERLERİ", accountCode: "791"},
    "VII.J.3.": {name: "MEMUR ÜCRET VE GİDERLERİ", accountCode: "792"},
    "VII.J.4.": {name: "DIŞARIDAN SAĞLANAN FAYDA VE HİZMETLER", accountCode: "793"},
    "VII.J.5.": {name: "ÇEŞİTLİ GİDERLER", accountCode: "794"},
    "VII.J.6.": {name: "VERGİ, RESİM VE HARÇLAR", accountCode: "795"},
    "VII.J.7.": {name: "AMORTİSMANLAR VE TÜKENME PAYLARI", accountCode: "796"},
    "VII.J.8.": {name: "FİNANSMAN GİDERLERİ", accountCode: "797"},
    "VII.J.9.": {name: "GİDER ÇEŞİTLERİ YANSITMA HESABI", accountCode: "798"},
    "VII.J.10.": {name: "ÜRETİM MALİYET HESABI", accountCode: "799"},
    "VIII.": {name: "(SERBEST)", accountCode: "8"},
    "IX.": {name: "NAZIM HESAPLAR", accountCode: "9"},
    "X.": {name: "(SERBEST)", accountCode: "0"},
}

export const FinancialService = {
    getDefaultFinancial() {

    }
}


