export const provinces = [
  { name: 'An Giang' },
  { name: 'Bà rịa Vũng Tàu' },
  { name: 'Bạc Liêu' },
  { name: 'Bắc Giang' },
  { name: 'Bắc Kạn' },
  { name: 'Bắc Ninh' },
  { name: 'Bến Tre' },
  { name: 'Bình Dương' },
  { name: 'Bình Định' },
  { name: 'Bình Phước' },
  { name: 'Bình Thuận' },
  { name: 'Cà Mau' },
  { name: 'Cao Bằng' },
  { name: 'Cần Thơ' },
  { name: 'Đà Nẵng' },
  { name: 'Đắk Lắk' },
  { name: 'Đắk Nông' },
  { name: 'Điện Biên' },
  { name: 'Đồng Nai' },
  { name: 'Đồng Tháp' },
  { name: 'Gia Lai' },
  { name: 'Hà Giang' },
  { name: 'Hà Nam' },
  { name: 'Hà Nội' },
  { name: 'Hà Tĩnh' },
  { name: 'Hải Dương' },
  { name: 'Hải Phòng' },
  { name: 'Hậu Giang' },
  { name: 'Hòa Bình' },
  { name: 'Hưng Yên' },
  { name: 'Khánh Hòa' },
  { name: 'Kiên Giang' },
  { name: 'Kon Tum' },
  { name: 'Lai Châu' },
  { name: 'Lạng Sơn' },
  { name: 'Lào Cai' },
  { name: 'Lâm Đồng' },
  { name: 'Long An' },
  { name: 'Nam Định' },
  { name: 'Nghệ An' },
  { name: 'Ninh Bình' },
  { name: 'Ninh Thuận' },
  { name: 'Phú Thọ' },
  { name: 'Phú Yên' },
  { name: 'Quảng Bình' },
  { name: 'Quảng Nam' },
  { name: 'Quảng Ngãi' },
  { name: 'Quảng Ninh' },
  { name: 'Quảng Trị' },
  { name: 'Sóc Trăng' },
  { name: 'Sơn La' },
  { name: 'Tây Ninh' },
  { name: 'Thái Bình' },
  { name: 'Thái Nguyên' },
  { name: 'Thanh Hóa' },
  { name: 'Thừa Thiên Huế' },
  { name: 'Tiền Giang' },
  { name: 'TP Hồ Chí Minh' },
  { name: 'Trà Vinh' },
  { name: 'Tuyên Quang' },
  { name: 'Vĩnh Long' },
  { name: 'Vĩnh Phúc' },
  { name: 'Yên Bái' },
]

export const districts = {
  'An Giang': [
    { name: 'Thành phố Long Xuyên' },
    { name: 'Thành phố Châu Đốc' },
    { name: 'Huyện An Phú' },
    { name: 'Thị xã Tân Châu' },
    { name: 'Huyện Phú Tân' },
    { name: 'Huyện Châu Phú' },
    { name: 'Huyện Tịnh Biên' },
    { name: 'Huyện Tri Tôn' },
    { name: 'Huyện Châu Thành' },
    { name: 'Huyện Chợ Mới' },
    { name: 'Huyện Thoại Sơn' },
  ],
  'Bà rịa Vũng Tàu': [
    { name: 'Thành phố Vũng Tàu' },
    { name: 'Thành phố Bà Rịa' },
    { name: 'Huyện Châu Đức' },
    { name: 'Huyện Xuyên Mộc' },
    { name: 'Huyện Long Điền' },
    { name: 'Huyện Đất Đỏ' },
    { name: 'Huyện Tân Thành' },
  ],
  'Bạc Liêu': [
    { name: 'Thành phố Bạc Liêu' },
    { name: 'Huyện Hồng Dân' },
    { name: 'Huyện Phước Long' },
    { name: 'Huyện Vĩnh Lợi' },
    { name: 'Thị xã Giá Rai' },
    { name: 'Huyện Đông Hải' },
    { name: 'Huyện Hoà Bình' },
  ],
  'Bắc Giang': [
    { name: 'Thành phố Bắc Giang' },
    { name: 'Huyện Yên Thế' },
    { name: 'Huyện Tân Yên' },
    { name: 'Huyện Lạng Giang' },
    { name: 'Huyện Lục Nam' },
    { name: 'Huyện Lục Ngạn' },
    { name: 'Huyện Sơn Động' },
    { name: 'Huyện Yên Dũng' },
    { name: 'Huyện Việt Yên' },
    { name: 'Huyện Hiệp Hòa' },
  ],
  'Bắc Kạn': [
    { name: 'Thành Phố Bắc Kạn' },
    { name: 'Huyện Pác Nặm' },
    { name: 'Huyện Ba Bể' },
    { name: 'Huyện Ngân Sơn' },
    { name: 'Huyện Bạch Thông' },
    { name: 'Huyện Chợ Đồn' },
    { name: 'Huyện Chợ Mới' },
    { name: 'Huyện Na Rì' },
  ],
  'Bắc Ninh': [
    { name: 'Thành phố Bắc Ninh' },
    { name: 'Huyện Yên Phong' },
    { name: 'Huyện Quế Võ' },
    { name: 'Huyện Tiên Du' },
    { name: 'Thị xã Từ Sơn' },
    { name: 'Huyện Thuận Thành' },
    { name: 'Huyện Gia Bình' },
    { name: 'Huyện Lương Tài' },
  ],
  'Bến Tre': [
    { name: 'Thành phố Bến Tre' },
    { name: 'Huyện Châu Thành' },
    { name: 'Huyện Chợ Lách' },
    { name: 'Huyện Mỏ Cày Nam' },
    { name: 'Huyện Giồng Trôm' },
    { name: 'Huyện Bình Đại' },
    { name: 'Huyện Ba Tri' },
    { name: 'Huyện Thạnh Phú' },
    { name: 'Huyện Mỏ Cày Bắc' },
  ],
  'Bình Dương': [
    { name: 'Thành phố Thủ Dầu Một' },
    { name: 'Huyện Bàu Bàng' },
    { name: 'Huyện Dầu Tiếng' },
    { name: 'Thị xã Bến Cát' },
    { name: 'Huyện Phú Giáo' },
    { name: 'Thị xã Tân Uyên' },
    { name: 'Thị xã Dĩ An' },
    { name: 'Thị xã Thuận An' },
    { name: 'Huyện Bắc Tân Uyên' },
  ],
  'Bình Định': [
    { name: 'Thành phố Qui Nhơn' },
    { name: 'Huyện An Lão' },
    { name: 'Huyện Hoài Nhơn' },
    { name: 'Huyện Hoài Ân' },
    { name: 'Huyện Phù Mỹ' },
    { name: 'Huyện Vĩnh Thạnh' },
    { name: 'Huyện Tây Sơn' },
    { name: 'Huyện Phù Cát' },
    { name: 'Thị xã An Nhơn' },
    { name: 'Huyện Tuy Phước' },
    { name: 'Huyện Vân Canh' },
  ],
  'Bình Phước': [
    { name: 'Thị xã Phước Long' },
    { name: 'Thị xã Đồng Xoài' },
    { name: 'Thị xã Bình Long' },
    { name: 'Huyện Bù Gia Mập' },
    { name: 'Huyện Lộc Ninh' },
    { name: 'Huyện Bù Đốp' },
    { name: 'Huyện Hớn Quản' },
    { name: 'Huyện Đồng Phú' },
    { name: 'Huyện Bù Đăng' },
    { name: 'Huyện Chơn Thành' },
    { name: 'Huyện Phú Riềng' },
  ],
  'Bình Thuận': [
    { name: 'Thành phố Phan Thiết' },
    { name: 'Thị xã La Gi' },
    { name: 'Huyện Tuy Phong' },
    { name: 'Huyện Bắc Bình' },
    { name: 'Huyện Hàm Thuận Bắc' },
    { name: 'Huyện Hàm Thuận Nam' },
    { name: 'Huyện Tánh Linh' },
    { name: 'Huyện Đức Linh' },
    { name: 'Huyện Hàm Tân' },
    { name: 'Huyện Phú Quí' },
  ],
  'Cà Mau': [
    { name: 'Thành phố Cà Mau' },
    { name: 'Huyện U Minh' },
    { name: 'Huyện Thới Bình' },
    { name: 'Huyện Trần Văn Thời' },
    { name: 'Huyện Cái Nước' },
    { name: 'Huyện Đầm Dơi' },
    { name: 'Huyện Năm Căn' },
    { name: 'Huyện Phú Tân' },
    { name: 'Huyện Ngọc Hiển' },
  ],
  'Cao Bằng': [
    { name: 'Thành phố Cao Bằng' },
    { name: 'Huyện Bảo Lâm' },
    { name: 'Huyện Bảo Lạc' },
    { name: 'Huyện Thông Nông' },
    { name: 'Huyện Hà Quảng' },
    { name: 'Huyện Trà Lĩnh' },
    { name: 'Huyện Trùng Khánh' },
    { name: 'Huyện Hạ Lang' },
    { name: 'Huyện Quảng Uyên' },
    { name: 'Huyện Phục Hoà' },
    { name: 'Huyện Hoà An' },
    { name: 'Huyện Nguyên Bình' },
    { name: 'Huyện Thạch An' },
  ],
  'Cần Thơ': [
    { name: 'Quận Ninh Kiều' },
    { name: 'Quận Ô Môn' },
    { name: 'Quận Bình Thuỷ' },
    { name: 'Quận Cái Răng' },
    { name: 'Quận Thốt Nốt' },
    { name: 'Huyện Vĩnh Thạnh' },
    { name: 'Huyện Cờ Đỏ' },
    { name: 'Huyện Phong Điền' },
    { name: 'Huyện Thới Lai' },
  ],
  'Đà Nẵng': [
    { name: 'Quận Liên Chiểu' },
    { name: 'Quận Thanh Khê' },
    { name: 'Quận Hải Châu' },
    { name: 'Quận Sơn Trà' },
    { name: 'Quận Ngũ Hành Sơn' },
    { name: 'Quận Cẩm Lệ' },
    { name: 'Huyện Hòa Vang' },
    { name: 'Huyện Hoàng Sa' },
  ],
  'Đăk Lăk': [
    { name: 'Thành phố Buôn Ma Thuột' },
    { name: 'Thị Xã Buôn Hồ' },
    { name: "Huyện Ea H'leo" },
    { name: 'Huyện Ea Súp' },
    { name: 'Huyện Buôn Đôn' },
    { name: "Huyện Cư M'gar" },
    { name: 'Huyện Krông Búk' },
    { name: 'Huyện Krông Năng' },
    { name: 'Huyện Ea Kar' },
    { name: "Huyện M'Đrắk" },
    { name: 'Huyện Krông Bông' },
    { name: 'Huyện Krông Pắc' },
    { name: 'Huyện Krông A Na' },
    { name: 'Huyện Lắk' },
    { name: 'Huyện Cư Kuin' },
  ],
  'Đăk Nông': [
    { name: 'Thị xã Gia Nghĩa' },
    { name: 'Huyện Đăk Glong' },
    { name: 'Huyện Cư Jút' },
    { name: 'Huyện Đắk Mil' },
    { name: 'Huyện Krông Nô' },
    { name: 'Huyện Đắk Song' },
    { name: "Huyện Đắk R'Lấp" },
    { name: 'Huyện Tuy Đức' },
  ],
  'Điện Biên': [
    { name: 'Thành phố Điện Biên Phủ' },
    { name: 'Thị Xã Mường Lay' },
    { name: 'Huyện Mường Nhé' },
    { name: 'Huyện Mường Chà' },
    { name: 'Huyện Tủa Chùa' },
    { name: 'Huyện Tuần Giáo' },
    { name: 'Huyện Điện Biên' },
    { name: 'Huyện Điện Biên Đông' },
    { name: 'Huyện Mường Ảng' },
    { name: 'Huyện Nậm Pồ' },
  ],
  'Đồng Nai': [
    { name: 'Thành phố Biên Hòa' },
    { name: 'Thị xã Long Khánh' },
    { name: 'Huyện Tân Phú' },
    { name: 'Huyện Vĩnh Cửu' },
    { name: 'Huyện Định Quán' },
    { name: 'Huyện Trảng Bom' },
    { name: 'Huyện Thống Nhất' },
    { name: 'Huyện Cẩm Mỹ' },
    { name: 'Huyện Long Thành' },
    { name: 'Huyện Xuân Lộc' },
    { name: 'Huyện Nhơn Trạch' },
  ],
  'Đồng Tháp': [
    { name: 'Thành phố Cao Lãnh' },
    { name: 'Thành phố Sa Đéc' },
    { name: 'Thị xã Hồng Ngự' },
    { name: 'Huyện Tân Hồng' },
    { name: 'Huyện Hồng Ngự' },
    { name: 'Huyện Tam Nông' },
    { name: 'Huyện Tháp Mười' },
    { name: 'Huyện Cao Lãnh' },
    { name: 'Huyện Thanh Bình' },
    { name: 'Huyện Lấp Vò' },
    { name: 'Huyện Lai Vung' },
    { name: 'Huyện Châu Thành' },
  ],
  'Gia Lai': [
    { name: 'Thành phố Pleiku' },
    { name: 'Thị xã An Khê' },
    { name: 'Thị xã Ayun Pa' },
    { name: 'Huyện KBang' },
    { name: 'Huyện Đăk Đoa' },
    { name: 'Huyện Chư Păh' },
    { name: 'Huyện Ia Grai' },
    { name: 'Huyện Mang Yang' },
    { name: 'Huyện Kông Chro' },
    { name: 'Huyện Đức Cơ' },
    { name: 'Huyện Chư Prông' },
    { name: 'Huyện Chư Sê' },
    { name: 'Huyện Đăk Pơ' },
    { name: 'Huyện Ia Pa' },
    { name: 'Huyện Krông Pa' },
    { name: 'Huyện Phú Thiện' },
    { name: 'Huyện Chư Pưh' },
  ],
  'Hà Giang': [
    { name: 'Thành phố Hà Giang' },
    { name: 'Huyện Đồng Văn' },
    { name: 'Huyện Mèo Vạc' },
    { name: 'Huyện Yên Minh' },
    { name: 'Huyện Quản Bạ' },
    { name: 'Huyện Vị Xuyên' },
    { name: 'Huyện Bắc Mê' },
    { name: 'Huyện Hoàng Su Phì' },
    { name: 'Huyện Xín Mần' },
    { name: 'Huyện Bắc Quang' },
    { name: 'Huyện Quang Bình' },
  ],
  'Hà Nam': [
    { name: 'Thành phố Phủ Lý' },
    { name: 'Huyện Duy Tiên' },
    { name: 'Huyện Kim Bảng' },
    { name: 'Huyện Thanh Liêm' },
    { name: 'Huyện Bình Lục' },
    { name: 'Huyện Lý Nhân' },
  ],
  'Hà Nội': [
    { name: 'Quận Ba Đình' },
    { name: 'Quận Hoàn Kiếm' },
    { name: 'Quận Tây Hồ' },
    { name: 'Quận Long Biên' },
    { name: 'Quận Cầu Giấy' },
    { name: 'Quận Đống Đa' },
    { name: 'Quận Hai Bà Trưng' },
    { name: 'Quận Hoàng Mai' },
    { name: 'Quận Thanh Xuân' },
    { name: 'Huyện Sóc Sơn' },
    { name: 'Huyện Đông Anh' },
    { name: 'Huyện Gia Lâm' },
    { name: 'Quận Nam Từ Liêm' },
    { name: 'Huyện Thanh Trì' },
    { name: 'Quận Bắc Từ Liêm' },
    { name: 'Huyện Mê Linh' },
    { name: 'Quận Hà Đông' },
    { name: 'Thị xã Sơn Tây' },
    { name: 'Huyện Ba Vì' },
    { name: 'Huyện Phúc Thọ' },
    { name: 'Huyện Đan Phượng' },
    { name: 'Huyện Hoài Đức' },
    { name: 'Huyện Quốc Oai' },
    { name: 'Huyện Thạch Thất' },
    { name: 'Huyện Chương Mỹ' },
    { name: 'Huyện Thanh Oai' },
    { name: 'Huyện Thường Tín' },
    { name: 'Huyện Phú Xuyên' },
    { name: 'Huyện Ứng Hòa' },
    { name: 'Huyện Mỹ Đức' },
  ],
  'Hà Tĩnh': [
    { name: 'Thành phố Hà Tĩnh' },
    { name: 'Thị xã Hồng Lĩnh' },
    { name: 'Huyện Hương Sơn' },
    { name: 'Huyện Đức Thọ' },
    { name: 'Huyện Vũ Quang' },
    { name: 'Huyện Nghi Xuân' },
    { name: 'Huyện Can Lộc' },
    { name: 'Huyện Hương Khê' },
    { name: 'Huyện Thạch Hà' },
    { name: 'Huyện Cẩm Xuyên' },
    { name: 'Huyện Kỳ Anh' },
    { name: 'Huyện Lộc Hà' },
    { name: 'Thị xã Kỳ Anh' },
  ],
  'Hải Dương': [
    { name: 'Thành phố Hải Dương' },
    { name: 'Thị xã Chí Linh' },
    { name: 'Huyện Nam Sách' },
    { name: 'Huyện Kinh Môn' },
    { name: 'Huyện Kim Thành' },
    { name: 'Huyện Thanh Hà' },
    { name: 'Huyện Cẩm Giàng' },
    { name: 'Huyện Bình Giang' },
    { name: 'Huyện Gia Lộc' },
    { name: 'Huyện Tứ Kỳ' },
    { name: 'Huyện Ninh Giang' },
    { name: 'Huyện Thanh Miện' },
  ],
  'Hải Phòng': [
    { name: 'Quận Hồng Bàng' },
    { name: 'Quận Ngô Quyền' },
    { name: 'Quận Lê Chân' },
    { name: 'Quận Hải An' },
    { name: 'Quận Kiến An' },
    { name: 'Quận Đồ Sơn' },
    { name: 'Quận Dương Kinh' },
    { name: 'Huyện Thuỷ Nguyên' },
    { name: 'Huyện An Dương' },
    { name: 'Huyện An Lão' },
    { name: 'Huyện Kiến Thuỵ' },
    { name: 'Huyện Tiên Lãng' },
    { name: 'Huyện Vĩnh Bảo' },
    { name: 'Huyện Cát Hải' },
  ],
  'Hậu Giang': [
    { name: 'Thành phố Vị Thanh' },
    { name: 'Thị xã Ngã Bảy' },
    { name: 'Huyện Châu Thành A' },
    { name: 'Huyện Châu Thành' },
    { name: 'Huyện Phụng Hiệp' },
    { name: 'Huyện Vị Thuỷ' },
    { name: 'Huyện Long Mỹ' },
    { name: 'Thị xã Long Mỹ' },
  ],
  'Hòa Bình': [
    { name: 'Thành phố Hòa Bình' },
    { name: 'Huyện Đà Bắc' },
    { name: 'Huyện Kỳ Sơn' },
    { name: 'Huyện Lương Sơn' },
    { name: 'Huyện Kim Bôi' },
    { name: 'Huyện Cao Phong' },
    { name: 'Huyện Tân Lạc' },
    { name: 'Huyện Mai Châu' },
    { name: 'Huyện Lạc Sơn' },
    { name: 'Huyện Yên Thủy' },
    { name: 'Huyện Lạc Thủy' },
  ],
  'Hưng Yên': [
    { name: 'Thành phố Hưng Yên' },
    { name: 'Huyện Văn Lâm' },
    { name: 'Huyện Văn Giang' },
    { name: 'Huyện Yên Mỹ' },
    { name: 'Huyện Mỹ Hào' },
    { name: 'Huyện Ân Thi' },
    { name: 'Huyện Khoái Châu' },
    { name: 'Huyện Kim Động' },
    { name: 'Huyện Tiên Lữ' },
    { name: 'Huyện Phù Cừ' },
  ],
  'Khánh Hòa': [
    { name: 'Thành phố Nha Trang' },
    { name: 'Thành phố Cam Ranh' },
    { name: 'Huyện Cam Lâm' },
    { name: 'Huyện Vạn Ninh' },
    { name: 'Thị xã Ninh Hòa' },
    { name: 'Huyện Khánh Vĩnh' },
    { name: 'Huyện Diên Khánh' },
    { name: 'Huyện Khánh Sơn' },
    { name: 'Huyện Trường Sa' },
  ],
  'Kiên Giang': [
    { name: 'Thành phố Rạch Giá' },
    { name: 'Thị xã Hà Tiên' },
    { name: 'Huyện Kiên Lương' },
    { name: 'Huyện Hòn Đất' },
    { name: 'Huyện Tân Hiệp' },
    { name: 'Huyện Châu Thành' },
    { name: 'Huyện Giồng Riềng' },
    { name: 'Huyện Gò Quao' },
    { name: 'Huyện An Biên' },
    { name: 'Huyện An Minh' },
    { name: 'Huyện Vĩnh Thuận' },
    { name: 'Huyện Phú Quốc' },
    { name: 'Huyện Kiên Hải' },
    { name: 'Huyện U Minh Thượng' },
    { name: 'Huyện Giang Thành' },
  ],
  'Kon Tum': [
    { name: 'Thành phố Kon Tum' },
    { name: 'Huyện Đắk Glei' },
    { name: 'Huyện Ngọc Hồi' },
    { name: 'Huyện Đắk Tô' },
    { name: 'Huyện Kon Plông' },
    { name: 'Huyện Kon Rẫy' },
    { name: 'Huyện Đắk Hà' },
    { name: 'Huyện Sa Thầy' },
    { name: 'Huyện Tu Mơ Rông' },
    { name: "Huyện Ia H' Drai" },
  ],
  'Lai Châu': [
    { name: 'Thành phố Lai Châu' },
    { name: 'Huyện Tam Đường' },
    { name: 'Huyện Mường Tè' },
    { name: 'Huyện Sìn Hồ' },
    { name: 'Huyện Phong Thổ' },
    { name: 'Huyện Than Uyên' },
    { name: 'Huyện Tân Uyên' },
    { name: 'Huyện Nậm Nhùn' },
  ],
  'Lạng Sơn': [
    { name: 'Thành phố Lạng Sơn' },
    { name: 'Huyện Tràng Định' },
    { name: 'Huyện Bình Gia' },
    { name: 'Huyện Văn Lãng' },
    { name: 'Huyện Cao Lộc' },
    { name: 'Huyện Văn Quan' },
    { name: 'Huyện Bắc Sơn' },
    { name: 'Huyện Hữu Lũng' },
    { name: 'Huyện Chi Lăng' },
    { name: 'Huyện Lộc Bình' },
    { name: 'Huyện Đình Lập' },
  ],
  'Lào Cai': [
    { name: 'Thành phố Lào Cai' },
    { name: 'Huyện Bát Xát' },
    { name: 'Huyện Mường Khương' },
    { name: 'Huyện Si Ma Cai' },
    { name: 'Huyện Bắc Hà' },
    { name: 'Huyện Bảo Thắng' },
    { name: 'Huyện Bảo Yên' },
    { name: 'Huyện Sa Pa' },
    { name: 'Huyện Văn Bàn' },
  ],
  'Lâm Đồng': [
    { name: 'Thành phố Đà Lạt' },
    { name: 'Thành phố Bảo Lộc' },
    { name: 'Huyện Đam Rông' },
    { name: 'Huyện Lạc Dương' },
    { name: 'Huyện Lâm Hà' },
    { name: 'Huyện Đơn Dương' },
    { name: 'Huyện Đức Trọng' },
    { name: 'Huyện Di Linh' },
    { name: 'Huyện Bảo Lâm' },
    { name: 'Huyện Đạ Huoai' },
    { name: 'Huyện Đạ Tẻh' },
    { name: 'Huyện Cát Tiên' },
  ],
  'Long An': [
    { name: 'Thành phố Tân An' },
    { name: 'Thị xã Kiến Tường' },
    { name: 'Huyện Tân Hưng' },
    { name: 'Huyện Vĩnh Hưng' },
    { name: 'Huyện Mộc Hóa' },
    { name: 'Huyện Tân Thạnh' },
    { name: 'Huyện Thạnh Hóa' },
    { name: 'Huyện Đức Huệ' },
    { name: 'Huyện Đức Hòa' },
    { name: 'Huyện Bến Lức' },
    { name: 'Huyện Thủ Thừa' },
    { name: 'Huyện Tân Trụ' },
    { name: 'Huyện Cần Đước' },
    { name: 'Huyện Cần Giuộc' },
    { name: 'Huyện Châu Thành' },
  ],
  'Nam Định': [
    { name: 'Thành phố Nam Định' },
    { name: 'Huyện Mỹ Lộc' },
    { name: 'Huyện Vụ Bản' },
    { name: 'Huyện Ý Yên' },
    { name: 'Huyện Nghĩa Hưng' },
    { name: 'Huyện Nam Trực' },
    { name: 'Huyện Trực Ninh' },
    { name: 'Huyện Xuân Trường' },
    { name: 'Huyện Giao Thủy' },
    { name: 'Huyện Hải Hậu' },
  ],
  'Nghệ An': [
    { name: 'Thành phố Vinh' },
    { name: 'Thị xã Cửa Lò' },
    { name: 'Thị xã Thái Hoà' },
    { name: 'Huyện Quế Phong' },
    { name: 'Huyện Quỳ Châu' },
    { name: 'Huyện Kỳ Sơn' },
    { name: 'Huyện Tương Dương' },
    { name: 'Huyện Nghĩa Đàn' },
    { name: 'Huyện Quỳ Hợp' },
    { name: 'Huyện Quỳnh Lưu' },
    { name: 'Huyện Con Cuông' },
    { name: 'Huyện Tân Kỳ' },
    { name: 'Huyện Anh Sơn' },
    { name: 'Huyện Diễn Châu' },
    { name: 'Huyện Yên Thành' },
    { name: 'Huyện Đô Lương' },
    { name: 'Huyện Thanh Chương' },
    { name: 'Huyện Nghi Lộc' },
    { name: 'Huyện Nam Đàn' },
    { name: 'Huyện Hưng Nguyên' },
    { name: 'Thị xã Hoàng Mai' },
  ],
  'Ninh Bình': [
    { name: 'Thành phố Ninh Bình' },
    { name: 'Thành phố Tam Điệp' },
    { name: 'Huyện Nho Quan' },
    { name: 'Huyện Gia Viễn' },
    { name: 'Huyện Hoa Lư' },
    { name: 'Huyện Yên Khánh' },
    { name: 'Huyện Kim Sơn' },
    { name: 'Huyện Yên Mô' },
  ],
  'Ninh Thuận': [
    { name: 'Thành phố Phan Rang-Tháp Chàm' },
    { name: 'Huyện Bác Ái' },
    { name: 'Huyện Ninh Sơn' },
    { name: 'Huyện Ninh Hải' },
    { name: 'Huyện Ninh Phước' },
    { name: 'Huyện Thuận Bắc' },
    { name: 'Huyện Thuận Nam' },
  ],
  'Phú Thọ': [
    { name: 'Thành phố Việt Trì' },
    { name: 'Thị xã Phú Thọ' },
    { name: 'Huyện Đoan Hùng' },
    { name: 'Huyện Hạ Hoà' },
    { name: 'Huyện Thanh Ba' },
    { name: 'Huyện Phù Ninh' },
    { name: 'Huyện Yên Lập' },
    { name: 'Huyện Cẩm Khê' },
    { name: 'Huyện Tam Nông' },
    { name: 'Huyện Lâm Thao' },
    { name: 'Huyện Thanh Sơn' },
    { name: 'Huyện Thanh Thuỷ' },
    { name: 'Huyện Tân Sơn' },
  ],
  'Phú Yên': [
    { name: 'Thành phố Tuy Hoà' },
    { name: 'Thị xã Sông Cầu' },
    { name: 'Huyện Đồng Xuân' },
    { name: 'Huyện Tuy An' },
    { name: 'Huyện Sơn Hòa' },
    { name: 'Huyện Sông Hinh' },
    { name: 'Huyện Tây Hoà' },
    { name: 'Huyện Phú Hoà' },
    { name: 'Huyện Đông Hòa' },
  ],
  'Quảng Bình': [
    { name: 'Thành Phố Đồng Hới' },
    { name: 'Huyện Minh Hóa' },
    { name: 'Huyện Tuyên Hóa' },
    { name: 'Huyện Quảng Trạch' },
    { name: 'Huyện Bố Trạch' },
    { name: 'Huyện Quảng Ninh' },
    { name: 'Huyện Lệ Thủy' },
    { name: 'Thị xã Ba Đồn' },
  ],
  'Quảng Nam': [
    { name: 'Thành phố Tam Kỳ' },
    { name: 'Thành phố Hội An' },
    { name: 'Huyện Tây Giang' },
    { name: 'Huyện Đông Giang' },
    { name: 'Huyện Đại Lộc' },
    { name: 'Thị xã Điện Bàn' },
    { name: 'Huyện Duy Xuyên' },
    { name: 'Huyện Quế Sơn' },
    { name: 'Huyện Nam Giang' },
    { name: 'Huyện Phước Sơn' },
    { name: 'Huyện Hiệp Đức' },
    { name: 'Huyện Thăng Bình' },
    { name: 'Huyện Tiên Phước' },
    { name: 'Huyện Bắc Trà My' },
    { name: 'Huyện Nam Trà My' },
    { name: 'Huyện Núi Thành' },
    { name: 'Huyện Phú Ninh' },
    { name: 'Huyện Nông Sơn' },
  ],
  'Quảng Ngãi': [
    { name: 'Thành phố Quảng Ngãi' },
    { name: 'Huyện Bình Sơn' },
    { name: 'Huyện Trà Bồng' },
    { name: 'Huyện Tây Trà' },
    { name: 'Huyện Sơn Tịnh' },
    { name: 'Huyện Tư Nghĩa' },
    { name: 'Huyện Sơn Hà' },
    { name: 'Huyện Sơn Tây' },
    { name: 'Huyện Minh Long' },
    { name: 'Huyện Nghĩa Hành' },
    { name: 'Huyện Mộ Đức' },
    { name: 'Huyện Đức Phổ' },
    { name: 'Huyện Ba Tơ' },
    { name: 'Huyện Lý Sơn' },
  ],
  'Quảng Ninh': [
    { name: 'Thành phố Hạ Long' },
    { name: 'Thành phố Móng Cái' },
    { name: 'Thành phố Cẩm Phả' },
    { name: 'Thành phố Uông Bí' },
    { name: 'Huyện Bình Liêu' },
    { name: 'Huyện Tiên Yên' },
    { name: 'Huyện Đầm Hà' },
    { name: 'Huyện Hải Hà' },
    { name: 'Huyện Ba Chẽ' },
    { name: 'Huyện Vân Đồn' },
    { name: 'Huyện Hoành Bồ' },
    { name: 'Thị xã Đông Triều' },
    { name: 'Thị xã Quảng Yên' },
    { name: 'Huyện Cô Tô' },
  ],
  'Quảng Trị': [
    { name: 'Thành phố Đông Hà' },
    { name: 'Thị xã Quảng Trị' },
    { name: 'Huyện Vĩnh Linh' },
    { name: 'Huyện Hướng Hóa' },
    { name: 'Huyện Gio Linh' },
    { name: 'Huyện Đa Krông' },
    { name: 'Huyện Cam Lộ' },
    { name: 'Huyện Triệu Phong' },
    { name: 'Huyện Hải Lăng' },
  ],
  'Sóc Trăng': [
    { name: 'Thành phố Sóc Trăng' },
    { name: 'Huyện Châu Thành' },
    { name: 'Huyện Kế Sách' },
    { name: 'Huyện Mỹ Tú' },
    { name: 'Huyện Cù Lao Dung' },
    { name: 'Huyện Long Phú' },
    { name: 'Huyện Mỹ Xuyên' },
    { name: 'Thị xã Ngã Năm' },
    { name: 'Huyện Thạnh Trị' },
    { name: 'Thị xã Vĩnh Châu' },
    { name: 'Huyện Trần Đề' },
  ],
  'Sơn La': [
    { name: 'Thành phố Sơn La' },
    { name: 'Huyện Quỳnh Nhai' },
    { name: 'Huyện Thuận Châu' },
    { name: 'Huyện Mường La' },
    { name: 'Huyện Bắc Yên' },
    { name: 'Huyện Phù Yên' },
    { name: 'Huyện Mộc Châu' },
    { name: 'Huyện Yên Châu' },
    { name: 'Huyện Mai Sơn' },
    { name: 'Huyện Sông Mã' },
    { name: 'Huyện Sốp Cộp' },
    { name: 'Huyện Vân Hồ' },
  ],
  'Tây Ninh': [
    { name: 'Thành phố Tây Ninh' },
    { name: 'Huyện Tân Biên' },
    { name: 'Huyện Tân Châu' },
    { name: 'Huyện Dương Minh Châu' },
    { name: 'Huyện Châu Thành' },
    { name: 'Huyện Hòa Thành' },
    { name: 'Huyện Gò Dầu' },
    { name: 'Huyện Bến Cầu' },
    { name: 'Huyện Trảng Bàng' },
  ],
  'Thái Bình': [
    { name: 'Thành phố Thái Bình' },
    { name: 'Huyện Quỳnh Phụ' },
    { name: 'Huyện Hưng Hà' },
    { name: 'Huyện Đông Hưng' },
    { name: 'Huyện Thái Thụy' },
    { name: 'Huyện Tiền Hải' },
    { name: 'Huyện Kiến Xương' },
    { name: 'Huyện Vũ Thư' },
  ],
  'Thái Nguyên': [
    { name: 'Thành phố Thái Nguyên' },
    { name: 'Thành phố Sông Công' },
    { name: 'Huyện Định Hóa' },
    { name: 'Huyện Phú Lương' },
    { name: 'Huyện Đồng Hỷ' },
    { name: 'Huyện Võ Nhai' },
    { name: 'Huyện Đại Từ' },
    { name: 'Thị xã Phổ Yên' },
    { name: 'Huyện Phú Bình' },
  ],
  'Thanh Hóa': [
    { name: 'Thành phố Thanh Hóa' },
    { name: 'Thị xã Bỉm Sơn' },
    { name: 'Thị xã Sầm Sơn' },
    { name: 'Huyện Mường Lát' },
    { name: 'Huyện Quan Hóa' },
    { name: 'Huyện Bá Thước' },
    { name: 'Huyện Quan Sơn' },
    { name: 'Huyện Lang Chánh' },
    { name: 'Huyện Ngọc Lặc' },
    { name: 'Huyện Cẩm Thủy' },
    { name: 'Huyện Thạch Thành' },
    { name: 'Huyện Hà Trung' },
    { name: 'Huyện Vĩnh Lộc' },
    { name: 'Huyện Yên Định' },
    { name: 'Huyện Thọ Xuân' },
    { name: 'Huyện Thường Xuân' },
    { name: 'Huyện Triệu Sơn' },
    { name: 'Huyện Thiệu Hóa' },
    { name: 'Huyện Hoằng Hóa' },
    { name: 'Huyện Hậu Lộc' },
    { name: 'Huyện Nga Sơn' },
    { name: 'Huyện Như Xuân' },
    { name: 'Huyện Như Thanh' },
    { name: 'Huyện Nông Cống' },
    { name: 'Huyện Đông Sơn' },
    { name: 'Huyện Quảng Xương' },
    { name: 'Huyện Tĩnh Gia' },
  ],
  'Thừa Thiên Huế': [
    { name: 'Thành phố Huế' },
    { name: 'Huyện Phong Điền' },
    { name: 'Huyện Quảng Điền' },
    { name: 'Huyện Phú Vang' },
    { name: 'Thị xã Hương Thủy' },
    { name: 'Thị xã Hương Trà' },
    { name: 'Huyện A Lưới' },
    { name: 'Huyện Phú Lộc' },
    { name: 'Huyện Nam Đông' },
  ],
  'Tiền Giang': [
    { name: 'Thành phố Mỹ Tho' },
    { name: 'Thị xã Gò Công' },
    { name: 'Thị xã Cai Lậy' },
    { name: 'Huyện Tân Phước' },
    { name: 'Huyện Cái Bè' },
    { name: 'Huyện Cai Lậy' },
    { name: 'Huyện Châu Thành' },
    { name: 'Huyện Chợ Gạo' },
    { name: 'Huyện Gò Công Tây' },
    { name: 'Huyện Gò Công Đông' },
    { name: 'Huyện Tân Phú Đông' },
  ],
  'TP Hồ Chí Minh': [
    { name: 'Quận 1' },
    { name: 'Quận 12' },
    { name: 'Quận Thủ Đức' },
    { name: 'Quận 9' },
    { name: 'Quận Gò Vấp' },
    { name: 'Quận Bình Thạnh' },
    { name: 'Quận Tân Bình' },
    { name: 'Quận Tân Phú' },
    { name: 'Quận Phú Nhuận' },
    { name: 'Quận 2' },
    { name: 'Quận 3' },
    { name: 'Quận 10' },
    { name: 'Quận 11' },
    { name: 'Quận 4' },
    { name: 'Quận 5' },
    { name: 'Quận 6' },
    { name: 'Quận 8' },
    { name: 'Quận Bình Tân' },
    { name: 'Quận 7' },
    { name: 'Huyện Củ Chi' },
    { name: 'Huyện Hóc Môn' },
    { name: 'Huyện Bình Chánh' },
    { name: 'Huyện Nhà Bè' },
    { name: 'Huyện Cần Giờ' },
  ],
  'Trà Vinh': [
    { name: 'Thành phố Trà Vinh' },
    { name: 'Huyện Càng Long' },
    { name: 'Huyện Cầu Kè' },
    { name: 'Huyện Tiểu Cần' },
    { name: 'Huyện Châu Thành' },
    { name: 'Huyện Cầu Ngang' },
    { name: 'Huyện Trà Cú' },
    { name: 'Huyện Duyên Hải' },
    { name: 'Thị xã Duyên Hải' },
  ],
  'Tuyên Quang': [
    { name: 'Thành phố Tuyên Quang' },
    { name: 'Huyện Lâm Bình' },
    { name: 'Huyện Nà Hang' },
    { name: 'Huyện Chiêm Hóa' },
    { name: 'Huyện Hàm Yên' },
    { name: 'Huyện Yên Sơn' },
    { name: 'Huyện Sơn Dương' },
  ],
  'Vĩnh Long': [
    { name: 'Thành phố Vĩnh Long' },
    { name: 'Huyện Long Hồ' },
    { name: 'Huyện Mang Thít' },
    { name: 'Huyện Vũng Liêm' },
    { name: 'Huyện Tam Bình' },
    { name: 'Thị xã Bình Minh' },
    { name: 'Huyện Trà Ôn' },
    { name: 'Huyện Bình Tân' },
  ],
  'Vĩnh Phúc': [
    { name: 'Thành phố Vĩnh Yên' },
    { name: 'Thị xã Phúc Yên' },
    { name: 'Huyện Lập Thạch' },
    { name: 'Huyện Tam Dương' },
    { name: 'Huyện Tam Đảo' },
    { name: 'Huyện Bình Xuyên' },
    { name: 'Huyện Yên Lạc' },
    { name: 'Huyện Vĩnh Tường' },
    { name: 'Huyện Sông Lô' },
  ],
  'Yên Bái': [
    { name: 'Thành phố Yên Bái' },
    { name: 'Thị xã Nghĩa Lộ' },
    { name: 'Huyện Lục Yên' },
    { name: 'Huyện Văn Yên' },
    { name: 'Huyện Mù Căng Chải' },
    { name: 'Huyện Trấn Yên' },
    { name: 'Huyện Trạm Tấu' },
    { name: 'Huyện Văn Chấn' },
    { name: 'Huyện Yên Bình' },
  ],
}
