###

http://api.mooc.oshsu.kg/public/api/v1/open/video/types
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5teWVkdS5vc2hzdS5rZy9wdWJsaWMvYXBpL21vb2MvbG9naW4iLCJpYXQiOjE3NTQzODYzMzAsImV4cCI6MTc1NDQxNTE5MCwibmJmIjoxNzU0Mzg2MzMwLCJqdGkiOiJjc0hhSkdqYVhsT1V1VkpPIiwic3ViIjoiNDY0NTYiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.E9dQ1RCISvf2psrA1iDf9CrYzExEKnZOgYq2XJ4cyXg
Content-Type: application/json 

###
# STREAMS GET

GET http://api.mooc.oshsu.kg/public/api/v1/teacher/stream?course_id=174
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5teWVkdS5vc2hzdS5rZy9wdWJsaWMvYXBpL21vb2MvbG9naW4iLCJpYXQiOjE3NTQ5ODg4NDQsImV4cCI6MTc1NTAxNzcwNCwibmJmIjoxNzU0OTg4ODQ0LCJqdGkiOiJRdmFvTXloM1hnSGxRSlFjIiwic3ViIjoiNDY0NTYiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.ksJzSop1ji0ImNIWNg6SDAgSCLBl00BW_-dBha_NqW8
Content-Type: application/json  

###
# test
GET http://api.mooc.oshsu.kg/public/api/v1/student/course/lessons
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5teWVkdS5vc2hzdS5rZy9wdWJsaWMvYXBpL21vb2MvbG9naW4iLCJpYXQiOjE3NTU4MzE3NjQsImV4cCI6MTc1NTg2MDYyNCwibmJmIjoxNzU1ODMxNzY0LCJqdGkiOiJiNG5UQ0pBVk8zemFXbEdxIiwic3ViIjoiNTAzMjciLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.L-VuLkrFQQKHRpd1WpzEIdh_ILwO21VPJrUiYyQcVQs
Content-Type: application/json  
